packages/genesys-spark-tokens/data/tokens.json
packages/genesys-spark-tokens/snapshot/css/gse-ui-formsAndInputs.css
packages/genesys-spark-tokens/snapshot/json/gse-ui-formsAndInputs.json
packages/genesys-spark-tokens/snapshot/less/gse-ui-formsAndInputs.less
packages/genesys-spark-tokens/snapshot/scss/_gse-ui-formsAndInputs.scss

refactor(tokens): tokens update

---

packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-calendar.scss
packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-picker.scss

added missing tokens
COMUI-1784

refactor(month-picker): added missing tokens

---

packages/genesys-spark-components/src/components/legacy/gux-action-toast-legacy/gux-action-toast.scss
packages/genesys-spark-components/src/components/legacy/gux-modal-legacy/gux-modal-legacy.scss
packages/genesys-spark-components/src/components/legacy/gux-notification-toast-legacy/gux-notification-toast.scss
packages/genesys-spark-components/src/components/legacy/gux-switch-legacy/gux-switch-item/gux-switch-item.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/gux-form-field-dropdown.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/gux-form-field-phone.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-select/gux-form-field-select.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-textarea/gux-form-field-textarea.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/gux-form-field-time-picker.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-zone-picker/gux-form-field-time-zone-picker.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/gux-form-field.scss
packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss
packages/genesys-spark-components/src/components/stable/gux-table/gux-table.scss
packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/gux-tab-advanced-list/gux-tab-advanced-list.scss
packages/genesys-spark-components/src/style/_typography.scss
packages/genesys-spark-components/src/style/style-reset-focusable.scss
packages/genesys-spark-components/src/style/style-reset-typography.scss
packages/genesys-spark-components/src/style/style.scss
packages/genesys-spark-components/stencil.config.ts

updated typeography mixins
COMUI-2274

refactor(typography): updated typeography mixins

---

packages/genesys-spark-components/src/components/stable/gux-text-highlight/gux-text-highlight.scss

addition of missing toknens
[COMUI-2347](https://inindca.atlassian.net/browse/COMUI-2347)
[COMUI-2347]: https://inindca.atlassian.net/browse/COMUI-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(text-highlight): addition of missing tokens

---

packages/genesys-spark-components/src/components/stable/gux-form-field/helper-components/gux-form-field-input-clear-button/gux-form-field-input-clear-button.scss

ux review comments
[COMUI-2405](https://inindca.atlassian.net/browse/COMUI-2405)
[COMUI-2405]: https://inindca.atlassian.net/browse/COMUI-2405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(input-clear-button): ux review comments

---

packages/genesys-spark-components/src/components/stable/gux-dismiss-button/gux-dismiss-button.scss

apply missing tokens
[COMUI-2352](https://inindca.atlassian.net/browse/COMUI-2352)
[COMUI-2352]: https://inindca.atlassian.net/browse/COMUI-2352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(dismiss-button): apply missing tokens

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss

https://inindca.atlassian.net/browse/COMUI-2371
List of UX fixes from design can be seen in this figma file: https://www.figma.com/file/ZtmFM79VYATifStJlAhyYn/V4-Testing?type=design&node-id=699-60376&mode=design&t=e2GCOEYm1wNGt5YG-0

fix(gux-datepicker): UX comment fixes

---

packages/genesys-spark-components/src/components/stable/gux-tag/gux-tag.scss

https://inindca.atlassian.net/browse/COMUI-2246

fix(gux-tag): token fixes

---

packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.scss
packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.scss
packages/genesys-spark-components/src/components/stable/gux-context-menu/gux-context-menu.scss
packages/genesys-spark-components/src/components/stable/gux-list/gux-list.scss
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.scss
packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar-menu-button/gux-table-toolbar-menu-button.scss
packages/genesys-spark-components/src/components/stable/gux-table/gux-table-select-menu/gux-table-select-menu.scss
packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.scss
packages/genesys-spark-components/src/style/_mixins.scss

fixed list container style
COMUI-2398

fix(list): fixed list container style

---

packages/genesys-spark-components/src/components/beta/gux-blank-state/gux-blank-state.tsx

add conditional for call-to-action slot
[COMUI-2241](https://inindca.atlassian.net/browse/COMUI-2241)
[COMUI-2241]: https://inindca.atlassian.net/browse/COMUI-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(blank-state): add conditional for call-to-action slot (backport)

---

packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.scss

addition of missing tokens
[COMUI-2255](https://inindca.atlassian.net/browse/COMUI-2255)
[COMUI-2255]: https://inindca.atlassian.net/browse/COMUI-2255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(time-picker): addition of missing tokens

---

packages/genesys-spark-components/scripts/stencil-wrapper.ts

support new domains
COMUI-2422

feat(domains): support new domains

---

packages/genesys-spark-components/src/components/stable/gux-toast/gux-toast.scss

ux-review comments
[COMUI-2372](https://inindca.atlassian.net/browse/COMUI-2372)
[COMUI-2372]: https://inindca.atlassian.net/browse/COMUI-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(toast): ux-review

---

packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-menu/gux-menu-option/gux-menu-option.scss

refactor(flyout-menu): missing tokens

---

packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.scss

missing tokens
[COMUI-2311](https://inindca.atlassian.net/browse/COMUI-2311)
[COMUI-2311]: https://inindca.atlassian.net/browse/COMUI-2311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(gux-time-picker): missing tokens

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.scss

refactor(color-picker): missing tokens

---

packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.scss

https://inindca.atlassian.net/browse/COMUI-2153

fix(gux-copy-to-clipboard): token fixes

---

packages/genesys-spark-components/src/utils/date/time-zone.spec.ts

test(time-picker): removed flaky tests

---

packages/genesys-spark-components/scripts/stencil-wrapper.ts

fixed default asset loading
COMUI-2421

fix(asset-loading): fixed default asset loading

---

packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.scss

https://inindca.atlassian.net/browse/COMUI-2412
Added a token for the border-radius for the arrow in the popover component.

fix(gux-popover): added token for arrow

---

.github/reviewer-lottery.yml
.prettierignore
package-lock.json
package.json
packages/genesys-spark-components/.prettierignore
packages/genesys-spark/.eslintignore
packages/genesys-spark/.eslintrc.json
packages/genesys-spark/.lintstagedrc.json
packages/genesys-spark/.prettierignore
packages/genesys-spark/README.md
packages/genesys-spark/package.json
packages/genesys-spark/rollup.config.js
packages/genesys-spark/src/hosts.ts
packages/genesys-spark/src/index.ts
packages/genesys-spark/src/loading.ts
packages/genesys-spark/test/loading.spec.ts
packages/genesys-spark/tsconfig.json

Mostly focused on getting linting working in genesys-spark

Linting improvements/fixes

---

packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.scss

prevent icon from shrinking
[COMUI-2170](https://inindca.atlassian.net/browse/COMUI-2170)
[COMUI-2170]: https://inindca.atlassian.net/browse/COMUI-2170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(copy-to-clipboard): prevent icon from shrinking

---

packages/genesys-spark-components/src/components/stable/gux-breadcrumbs/breadcrumb-item/gux-breadcrumb-item.scss
packages/genesys-spark-components/src/components/stable/gux-breadcrumbs/breadcrumb-item/readme.md

Closes [COMUI-2428](https://inindca.atlassian.net/browse/COMUI-2428)
[COMUI-2428]: https://inindca.atlassian.net/browse/COMUI-2428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(breadcrumb): adding focus tokens

---

packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.scss
packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.scss

Closes [COMUI-2285](https://inindca.atlassian.net/browse/COMUI-2285)
[COMUI-2285]: https://inindca.atlassian.net/browse/COMUI-2285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(dropdown,dropdown-multi): adding missing gux-filter-suggestion tokens

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.scss

addition of missing tokens
COMUI-2410

refactor(form-field-range): addition of missing tokens

---

packages/genesys-spark-components/src/components/legacy/gux-action-toast-legacy/gux-action-toast.light.scss
packages/genesys-spark-components/src/style/style-reset-focusable.scss
packages/genesys-spark-components/src/style/style.scss

added missing utility classes
COMUI-2458

fix(focus-style): added missing utility classes

---

packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab-list/gux-tab-list.scss
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab-panel/gux-tab-panel.scss
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab/gux-tab.scss

refactor(tabs): missing tokens

---

web-apps/genesys-spark-examples/Jenkinsfile

prepare main to release beta
COMUI-2191

chore(build): prepare main to release beta

---

packages/genesys-spark-components/src/components/stable/gux-blank-state/gux-blank-state.scss

changed min widt of large version
COMUI-2242

fix(blank-state): changed min widt of large version

---

packages/genesys-spark-components/src/components/stable/gux-loading-message/gux-loading-message.scss

added max width restriction
COMUI-2264

fix(loading-message): added max width restriction

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/functional-components/gux-form-field-help/gux-form-field-help.scss

ux review comments
[COMUI-2404](https://inindca.atlassian.net/browse/COMUI-2404)
[COMUI-2404]: https://inindca.atlassian.net/browse/COMUI-2404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(form-field-checkbox): ux review comments

---

packages/genesys-spark-components/src/components/stable/gux-popover/example.html

update example file to match figma
[COMUI-2343](https://inindca.atlassian.net/browse/COMUI-2343)
[COMUI-2343]: https://inindca.atlassian.net/browse/COMUI-2343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(popover): update example file to match figma

---

packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control-item/gux-segmented-control-item.scss

fixed design system tokens
COMUI-2294

fix(segmented-control): fixed design system tokens

---

packages/genesys-spark-components/src/components/stable/gux-blank-state/readme.md
packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/gux-pagination-cursor.tsx
packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/readme.md
packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/readme.md

Closes [COMUI-2470](https://inindca.atlassian.net/browse/COMUI-2470)
[COMUI-2470]: https://inindca.atlassian.net/browse/COMUI-2470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(pagination-cursor): fixing missing items per page dropdown

---

packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/gux-time-zone-picker.scss

ux review comments
[COMUI-2464](https://inindca.atlassian.net/browse/COMUI-2464)
[COMUI-2464]: https://inindca.atlassian.net/browse/COMUI-2464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(time-zone-picker-beta): ux review comments

---

packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control-item/gux-segmented-control-item.scss
packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control-item/readme.md
packages/genesys-spark-components/src/components/stable/gux-blank-state/readme.md

added pointer cursor
COMUI-2475

fix(segmented-control): added pointer cursor

---

packages/genesys-spark-components/src/components/stable/gux-column-manager/gux-column-manager-item/gux-column-manager-item.scss
packages/genesys-spark-components/src/components/stable/gux-text-highlight/gux-text-highlight.scss

fix text highlighting
COMUI-2448

fix(column-manager): fix text highlighting

---

packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab/gux-tab.scss
packages/genesys-spark-components/src/components/stable/gux-tooltip-title/gux-tooltip-title.scss

fixed tab UX issues
COMUI-2472

fix(tabs): fixed tab UX issues

---

packages/genesys-spark-components/src/components/stable/gux-context-menu/gux-context-menu.tsx
packages/genesys-spark-components/src/components/stable/gux-context-menu/tests/__snapshots__/gux-context-menu.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-popup/gux-popup.tsx
packages/genesys-spark-components/src/components/stable/gux-popup/readme.md

feat(gux-popup): add offset property to gux-popup

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/gux-form-field-dropdown.tsx
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/gux-form-field-phone.tsx
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/gux-form-field-time-picker.tsx
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/tests/__snapshots__/gux-form-field-time-picker.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-zone-picker/gux-form-field-time-zone-picker.tsx
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-zone-picker/tests/__snapshots__/gux-form-field-time-zone-picker.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-zone-picker/tests/__snapshots__/gux-form-field-time-zone-picker.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/functional-components/gux-form-field-fieldset-container/gux-form-field-fieldset-container.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/functional-components/gux-form-field-legend-label/gux-form-field-legend-label.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/functional-components/gux-form-field-legend-label/gux-form-field-legend-label.tsx

Closes [COMUI-2466](https://inindca.atlassian.net/browse/COMUI-2466)
[COMUI-2466]: https://inindca.atlassian.net/browse/COMUI-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(form-field-legend-label): fixing beside label placement for Safari

---

packages/genesys-spark-components/src/components/stable/gux-list/gux-list-divider/gux-list-divider.scss
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.scss
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.scss

Closes [COMUI-2269](https://inindca.atlassian.net/browse/COMUI-2269) and [COMUI-2258](https://inindca.atlassian.net/browse/COMUI-2258)
[COMUI-2269]: https://inindca.atlassian.net/browse/COMUI-2269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[COMUI-2258]: https://inindca.atlassian.net/browse/COMUI-2258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(listbox,listbox-multi,list-divider): adding missing tokens

---

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.scss

add missing stylings for label.
Does anyone know is there away to increase thickness of the icon ?
[COMUI-2477](https://inindca.atlassian.net/browse/COMUI-2477)
[COMUI-2477]: https://inindca.atlassian.net/browse/COMUI-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(toggle): add missing stylings for label

---

docs/migration-guides/v4/gux-switch-legacy.md

improved migration guide
COMUI-2487

docs(switch-legacy): improved migration guide

---

packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-list/gux-month-list-item/gux-month-list-item.scss

fix(month-picker): fixed styles

---

packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.scss

fix(time-picker): fixed focus styles

---

packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.scss
packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.tsx

prevent selection of text in disabled input
COMUI-2484

refactor(phone-input): prevent selection of text in disabled input

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss

https://inindca.atlassian.net/browse/COMUI-2371
This PR fixes issues 2 and 3 from the design feedback here: https://www.figma.com/file/ZtmFM79VYATifStJlAhyYn/V4-Testing?type=design&node-id=699%3A60362&mode=design&t=5RVNhDkpmRVz6DCw-1

fix(gux-datepicker): fixed icon focus styling

---

packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-flyout-menu.scss
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-menu/gux-menu.scss
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-menu/gux-submenu/gux-submenu.scss
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-menu/gux-submenu/gux-submenu.tsx

fix(flyout-menu): fixed UX issues

---

packages/genesys-spark-components/.lintstagedrc.json
packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.scss
packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control-item/gux-segmented-control-item.scss
packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/gux-time-zone-picker.scss
packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.scss
packages/genesys-spark-components/src/components/stable/gux-column-manager/gux-column-manager-item/gux-column-manager-item.scss
packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-flyout-menu.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/helper-components/gux-form-field-input-clear-button/gux-form-field-input-clear-button.scss
packages/genesys-spark-components/src/components/stable/gux-loading-message/gux-loading-message.scss
packages/genesys-spark-components/src/components/stable/gux-rating/gux-rating.scss
packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/gux-tab-advanced/gux-tab-advanced.scss
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab-list/gux-tab-list.scss
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab/gux-tab.scss
packages/genesys-spark-components/src/style/style.scss
packages/genesys-spark/test/hosts.spec.ts

style(lint): linted codebase

---

packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.scss

ux review comments
[COMUI-2403](https://inindca.atlassian.net/browse/COMUI-2403)
[COMUI-2403]: https://inindca.atlassian.net/browse/COMUI-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(phone-input): ux review comments

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.light.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.scss
packages/genesys-spark-components/src/style/style.scss

https://inindca.atlassian.net/browse/COMUI-2406
Added border styling.

fix(gux-form-field-color): added border styles

---

docs/migration-guides/v4/readme.md

docs(migration-guide): various fixes identified in bug hunt

---

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.less
packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.tsx
packages/genesys-spark-components/src/components/stable/gux-toggle/tests/gux-toggle.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-toggle/tests/gux-toggle.spec.ts

prevent clickable area expanding past toggle-slider
COMUI-2486

fix(toggle): prevent clickable area expanding past toggle-slider

---

packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.tsx

remove stylings if same date selected
[COMUI-2460](https://inindca.atlassian.net/browse/COMUI-2460)
Will be backported to `v3`
[COMUI-2460]: https://inindca.atlassian.net/browse/COMUI-2460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(calendar): remove stylings if same date selected

---

packages/genesys-spark-components/src/components/stable/gux-list/gux-list-item/gux-list-item.scss

fixed alignment of list item
COMUI-2491

fix(context-menu): fixed alignment of list item

---

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.scss
packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.scss

https://inindca.atlassian.net/browse/COMUI-2332
Added some missing tokens and while I was at it I fixed the alignment and spacing for the error container.
I created this separate ticket for us to tackle once design creates a token for the animation duration in the future. Design will need to discuss this further, so I removed that missing token from this PR to address in a future PR. https://inindca.atlassian.net/browse/COMUI-2509

fix(gux-toggle): missing token fixes

---

packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.scss

fix(button-multi): fixed css token

---

packages/genesys-spark-components/src/components/legacy/gux-switch-legacy/gux-switch-item/gux-switch-item.scss

Added focus-visible ring
COMUI-2490

fix(switch-legacy): added focus-visible ring

---

packages/genesys-spark-components/src/components/legacy/gux-disclosure-button-legacy/gux-disclosure-button.scss

fix(disclosure-button): added focus state

---

package-lock.json
package.json
packages/genesys-spark-components-react/package.json
packages/genesys-spark-components/package.json
packages/genesys-spark/package.json
web-apps/genesys-spark-examples/package.json

fixed version number
COMUI-2191

build(version): fixed version number

---

packages/genesys-spark-components/src/components/stable/gux-switch/gux-switch-item/gux-switch-item.less

Added focus visible ring
COMUI-2490

feat(switch): added focus visible ring

---

packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx

fixed keyboard navigation issue
COMUI-2445

fix(dropdown): fixed keyboard navigation issue

---

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.scss
packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.tsx
packages/genesys-spark-components/src/components/stable/gux-toggle/tests/__snapshots__/gux-toggle.spec.ts.snap

Open to opinions on this change,
The new icon that was added did not fit the switch div correctly so I opted to update the positioning and change with width slightly on the icon.
I am thinking maybe just to request a smaller `icon` ?
[COMUI-2477](https://inindca.atlassian.net/browse/COMUI-2477)
[COMUI-2477]: https://inindca.atlassian.net/browse/COMUI-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(toggle): addition of new check icon

---

packages/genesys-spark-components/src/components/stable/gux-rating/gux-rating.scss
packages/genesys-spark-tokens/data/tokens.json
packages/genesys-spark-tokens/snapshot/css/gse-ui.css
packages/genesys-spark-tokens/snapshot/json/gse-ui.json
packages/genesys-spark-tokens/snapshot/less/gse-ui.less
packages/genesys-spark-tokens/snapshot/scss/_gse-ui.scss

Applying gap between stars & allowing stars to distribute evenly if a width is applied to gux-rating itself.

feat(rating): adding space and some flexibility for component width

---

packages/genesys-spark-tokens/data/tokens.json

Added some missing text style tokens. 🔤
- [Jira Issue](https://inindca.atlassian.net/browse/GDS-2188?atlOrigin=eyJpIjoiZGMyMWIyZGRlOWYxNGU4ZmJkOTUwZDBmMDAyN2JiM2EiLCJwIjoiaiJ9)
- [Figma branch](https://www.figma.com/file/JKbHmcf4nUF6C7Pj8M6MpY/branch/afyQBSykfNVmKZQfshjIm3/Spark%3A-Flare-4.0---Core?type=design&mode=design&t=mGej9Z7qo8mCm5GM-1)
- Set your plugin to the branch **feature/GDS-2188_update_text_styles**, and check the styles on the core set.

[GDS-2188] Added new text styles

---

packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.service.ts
packages/genesys-spark-components/src/components/stable/gux-time-picker/tests/gux-time-picker.service.spec.ts

set ko, zh-CN and zh-CN locales to use 24h clock
COMUI-2338

feat(time-picker): set ko, zh-CN and zh-CN locales to use 24h clock

---

packages/genesys-spark-components/src/components/stable/gux-tabs/example.html
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tabs.scss

I found the fix for this issue here https://moduscreate.com/blog/how-to-fix-overflow-issues-in-css-flex-layouts/
Will need to backport to v3

fix(gux-tabs): fix scroll behavior in gux-tab-panel

---

packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.scss

Set bg color to token
GSD-2251
Does this need to be backported to V3?

feat(phone-input): set bg color to token

---

packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/gux-option-multi.scss

Make option svg 16 by 16
GDS-2239
Does this need to be backported?
Also, this is hacky so if anyone knows a better option here, happy to try it.

feat(dropdown-multi): make option svg 16 by 16

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.scss

Align input and label
GSD-2249
Does this need to be backported to V3?

feat(form-field-radio): align input and label

---

packages/genesys-spark-components/src/components/stable/gux-badge/gux-badge.scss
packages/genesys-spark-components/src/components/stable/gux-tooltip-title/gux-tooltip-title.scss

Centred icon in badge
GSD-2243
Does this need to be backported to v3?

feat(badge): centred icon in badge

---

packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.tsx
packages/genesys-spark-components/src/components/stable/gux-table-toolbar/readme.md

Open to opinions on this change,
After reviewing this issue I think the best solution is to expose a method that the end user can call.
Once this is merged I will backport to v3 and also notify the developer of the method maybe I should include example in the examples file ?
[COMUI-2385](https://inindca.atlassian.net/browse/COMUI-2385)
[COMUI-2385]: https://inindca.atlassian.net/browse/COMUI-2385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(table-toolbar): table-toolbar may fail to condense if text changes dynamically

---

packages/genesys-spark-tokens/utils/get-token-studio-tokens.mjs

fix(token): fixed token build

---

packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/gux-time-zone-picker.less

remove stylings from gux-list-divider
https://inindca.atlassian.net/browse/COMUI-2383

fix(time-zone-picker): remove stylings from gux-list-divider

---

packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.tsx

feat(gux-tooltip): add support for updating for attribute

---

packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.scss

set host pointer-events to none
COMUI-2171

fix(tooltip): set host pointer-events to none

---

packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/gux-time-zone-picker.tsx

This change makes sense to me, I have raised it with UX also just awaiting a response.
[COMUI-2380](https://inindca.atlassian.net/browse/COMUI-2380)
[COMUI-2380]: https://inindca.atlassian.net/browse/COMUI-2380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(time-zone-picker): conditionally render defaults header

---

docs/CONTRIBUTING.md
package.json

Also adds `npm start` which is the usual expected way to run things locally
COMUI-2098

docs(contributing): add instructions for running locally, fix document links

---

packages/genesys-spark-components/src/components/stable/gux-button/gux-button.scss

centre icon in icon only button
GDS-2290

feat(button): centre icon in icon only button

---

packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.less

fixed selected date on previouse month css
COMUI-2538

fix(calendar): fixed selected date on previouse month css

---

packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar.tsx

table-toolbar may fail to condense if text changes dynamically
[COMUI-2385](https://inindca.atlassian.net/browse/COMUI-2385)
[COMUI-2385]: https://inindca.atlassian.net/browse/COMUI-2385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(table-toolbar): table-toolbar may fail to condense if text changes dynamically 

---

packages/genesys-spark-components/src/components/beta/gux-segmented-control/example.html

Remove extra example instance for expand
GDS-2285

feat(segmented-control): remove extra example instance for expand

---

docs/migration-guides/v4/color-palette.md
docs/migration-guides/v4/shadows.md
docs/migration-guides/v4/spacing.md

Open to opinions and changes to the migration docs,
[You can view the changes here ](https://github.com/MyPureCloud/genesys-spark/blob/feature/COMUI-2553/docs/migration-guides/v4/readme.md#tokenization--css-variables)
Ticket : https://inindca.atlassian.net/browse/COMUI-2553

docs(migration) - migration docs updates

---

packages/genesys-spark-tokens/data/tokens.json
packages/genesys-spark-tokens/snapshot/css/gse-ui.css
packages/genesys-spark-tokens/snapshot/json/gse-ui.json
packages/genesys-spark-tokens/snapshot/less/gse-ui.less
packages/genesys-spark-tokens/snapshot/scss/_gse-ui.scss

Updated badge border radius value to enable the fix for this issue:
https://inindca.atlassian.net/browse/GDS-2243

fix(tokens): updated border radius value for badge

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/example.html
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.tsx
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/tests/__snapshots__/gux-form-field-text-like.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/tests/__snapshots__/gux-form-field-text-like.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/tests/gux-form-field-text-like.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/tests/gux-form-field-text-like.spec.ts

feat(form-field-text-like): add loading spinner

---

packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-buttons-beta/gux-pagination-buttons-beta.tsx
packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-buttons-beta/i18n/en.json
packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-buttons-beta/tests/__snapshots__/gux-pagination-buttons-beta.spec.ts.snap
packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/i18n/en.json
packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/tests/__snapshots__/gux-pagination-items-per-page-beta.spec.ts.snap
packages/genesys-spark-components/src/components/beta/gux-pagination-beta/tests/__snapshots__/gux-pagination-beta.spec.ts.snap
packages/genesys-spark-components/src/i18n/translations/en.json

improving accessibility
[COMUI-803](https://inindca.atlassian.net/browse/COMUI-803)
[COMUI-803]: https://inindca.atlassian.net/browse/COMUI-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(pagination-beta): improving accessibility

---

packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-buttons.tsx
packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-buttons/i18n/en.json
packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-buttons/tests/__snapshots__/gux-pagination-buttons.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/i18n/en.json
packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/tests/__snapshots__/gux-pagination-items-per-page.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-pagination/tests/__snapshots__/gux-pagination.spec.ts.snap
packages/genesys-spark-components/src/i18n/translations/en.json

improving accessibility
Will create a back-port for this in v3 also for `pagination-beta`
[COMUI-803](https://inindca.atlassian.net/browse/COMUI-803)
[COMUI-803]: https://inindca.atlassian.net/browse/COMUI-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(pagination): improving accessibility

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/gux-form-field-dropdown.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/gux-form-field-dropdown.tsx
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap

remove extra disabled styling
https://inindca.atlassian.net/browse/COMUI-1761

feat(form-field-dropdown): remove extra disabled styling

---

packages/genesys-spark-components/scripts/generate-component-data.js
packages/genesys-spark-components/src/components/stable/gux-listbox/example.html
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.service.ts
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox/option-group/gux-option-group.scss
packages/genesys-spark-components/src/components/stable/gux-listbox/option-group/gux-option-group.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox/option-group/readme.md

Add grouping to listbox
GDS-2287

feat(listbox): add grouping to listbox

---

packages/genesys-spark-components/src/components/stable/gux-list/gux-list-divider/readme.md
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.service.ts
packages/genesys-spark-components/src/components/stable/gux-listbox/option-group/readme.md

fix(dropdown-multi): fix tests

---

packages/genesys-spark-components/src/components/stable/gux-dropdown/example.html
packages/genesys-spark-components/src/components/stable/gux-dropdown/tests/__snapshots__/gux-dropdown.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-dropdown/tests/gux-dropdown.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-dropdown/tests/gux-dropdown.spec.ts
packages/genesys-spark-components/src/components/stable/gux-listbox/option-group/gux-option-group.scss
packages/genesys-spark-components/src/components/stable/gux-listbox/option-group/gux-option-group.tsx

Add display changes when options are filtered
Handle the divider display logic

feat(option-group): Add display changes when options are filtered

---

.prettierignore
package-lock.json
packages/genesys-spark-components/.stylelintrc.json
packages/genesys-spark-components/package.json
packages/genesys-spark-components/src/components/stable/gux-button-slot/example.html
packages/genesys-spark-components/src/components/stable/gux-button-slot/gux-button-slot.scss
packages/genesys-spark-components/src/components/stable/gux-button/example.html
packages/genesys-spark-components/src/components/stable/gux-button/gux-button.scss

button and button-slot now use logical css properties to support rtl text direction
COMUI-2592

fix(logical-css): button and button-slot now use logical css properties

---

packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab/gux-tab.scss

removed fixed width from gux-tab
[COMUI-2573](https://inindca.atlassian.net/browse/COMUI-2573)
[COMUI-2573]: https://inindca.atlassian.net/browse/COMUI-2573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(tab): removed fixed width from gux-tab

---

packages/genesys-spark-components/src/style/examples/typography.html
packages/genesys-spark-components/src/style/style-reset-typography.scss

Update the typography page
GDS-2292

feat(type page): update the typography page

---

packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.scss

Remove fixed width for filter
GDS-1941

feat(table-toolbar): remove fixed width for filter

---

web-apps/genesys-spark-examples/src/styles/component-viewer.scss

surpressed overlay error
COMUI-2597

build(webpack): surpressed overlay error

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss

fixed font size bug
COMUI-2224

fix(datepicker): fixed font size bug

---

packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar-action/gux-table-toolbar-action.tsx
packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.scss
packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.tsx
packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar-custom-action/tests/__snapshots__/gux-table-toolbar-custom-action.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar-custom-action/tests/gux-table-toolbar-custom-action.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar-custom-action/tests/gux-table-toolbar-custom-action.spec.ts

fixed click event firing when disabled
COMUI-2302

fix(toolbar-custom-action): fixed click event firing when disabled

---

packages/genesys-spark-components/src/components/stable/gux-accordion/example.html
packages/genesys-spark-components/src/components/stable/gux-accordion/gux-accordion-section/gux-accordion-section.tsx
packages/genesys-spark-components/src/components/stable/gux-accordion/gux-accordion-section/readme.md
packages/genesys-spark-components/src/components/stable/gux-accordion/gux-accordion.tsx

added open and close events
COMUI-2586

feat(accordion): added open and close events

---

packages/genesys-spark-components/src/components/beta/gux-avatar/example.html
packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar.scss
packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar.tsx
packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar.types.ts
packages/genesys-spark-components/src/components/beta/gux-avatar/readme.md
packages/genesys-spark-components/src/components/beta/gux-avatar/tests/__snapshots__/gux-avatar.spec.ts.snap
packages/genesys-spark-components/src/components/beta/gux-avatar/tests/gux-avatar.spec.ts
packages/genesys-spark-tokens/data/tokens.json
packages/genesys-spark-tokens/snapshot/css/gse-ui-dataDisplay.css
packages/genesys-spark-tokens/snapshot/json/gse-ui-dataDisplay.json
packages/genesys-spark-tokens/snapshot/less/gse-ui-dataDisplay.less
packages/genesys-spark-tokens/snapshot/scss/_gse-ui-dataDisplay.scss

feat(avatar): basic avatar implementation: sizes and initials only

---

packages/genesys-spark-components/src/components/stable/gux-popover-list/gux-popover-list.tsx
packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.tsx

added press Escape to close functionality
COMUI-2167

feat(popover): added press Escape to close functionality

---

playground/vue-3/index.html

For Spike https://inindca.atlassian.net/browse/COMUI-2595

chore(dropdown): adding Vue playground example of a dynamic loading dropdown on open

---

packages/genesys-spark-components/src/components/stable/gux-table/gux-all-row-select/readme.md

Title points to another component. Just changing to the right one.

docs(all-row-select): update title of readme

---

packages/genesys-spark-components/src/components/beta/gux-dropdown-multi/gux-dropdown-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/gux-option-multi.less
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/gux-option-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.service.ts

elements cannot be navigated with keyboard
[COMUI-2660](https://inindca.atlassian.net/browse/COMUI-2660)
[COMUI-2660]: https://inindca.atlassian.net/browse/COMUI-2660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown-multi): elements cannot be navigated with keyboard

---

packages/genesys-spark-components/src/components/beta/gux-calendar-beta/components/single/gux-calendar.tsx

when date selected it will select day before
[COMUI-2456](https://inindca.atlassian.net/browse/COMUI-2456)
[COMUI-2456]: https://inindca.atlassian.net/browse/COMUI-2456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(calendar-beta): when date selected it will select day before

---

packages/genesys-spark-components/src/components/beta/gux-time-picker/gux-time-picker.less

[COMUI-2659](https://inindca.atlassian.net/browse/COMUI-2659)
[COMUI-2659]: https://inindca.atlassian.net/browse/COMUI-2659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(time-picker-beta): AM/PM button does not inherit visibility css property when set on component

---

packages/genesys-spark-components/src/components/stable/gux-table/gux-all-row-select/gux-all-row-select.tsx
packages/genesys-spark-components/src/components/stable/gux-table/gux-row-select/gux-row-select.tsx

selected value not updating to reflect checkbox state
[COMUI-2557](https://inindca.atlassian.net/browse/COMUI-2557)
[COMUI-2557]: https://inindca.atlassian.net/browse/COMUI-2557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(gux-table): selected value not updating to reflect checbox state

---

package-lock.json
packages/genesys-spark/package.json
web-apps/genesys-spark-examples/package.json

updated some dependencies to latest
COMUI-2634

build(dependencies): updated some dependencies to latest

---

package-lock.json
packages/genesys-spark-components/package.json

upgraded some dependencies to latest
COMUI-2634

chore(dependencies): upgraded some dependencies to latest

---

packages/genesys-spark-tokens/package.json

fix(tests): fixed ci test script

---

web-apps/genesys-spark-examples/scripts/generate-versions-file.mjs

fix(docs): hide v5

---

packages/genesys-spark-components/src/style/examples/typography.html

Noticed the display is broken on Firefox. This change should address that

fix(type example): fix dodgy Firefox version

---

packages/genesys-spark-components/scripts/copy-genesys-spark-utils.mjs
packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar.tsx
packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox/option-group/gux-option-group.tsx
shared-configs/eslint-config-genesys-spark-components/index.js
shared-configs/eslint-config-genesys-spark-components/typescript.js

build(eslint): added eslint curly rule

---

packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-picker.less
packages/genesys-spark-components/src/components/stable/gux-content-search/gux-content-search.less
packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.less

Change focus rings on items with an outer focus visible with them to small. 
COMUI-2674

feat(monthpicker datepicker): change calendar focus ring to small

---

packages/genesys-spark-components/src/components/stable/gux-context-menu/gux-context-menu.scss

feat(gux-context-menu): adopt new tokens

---

packages/genesys-spark/package.json

fix(genesys-spark): fixed broken types reference

---

packages/genesys-spark-components/src/components/beta/gux-date-time/example.html

feat(date-time): use current time in date-time example

---

packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/gux-pagination-items-per-page.scss

feat(pagination): change dropdown size to fit-content

---

packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-items-per-page-beta/gux-pagination-items-per-page-beta.less

feat(pagination): change width to fit-content

---

packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.scss
packages/genesys-spark/src/style/_mixins.scss

I am not 100% happy with this solution but it will prevent the initial glitchy render on-load when the component is trying to figure out what layout to use. I wasnt sure should I dig deep into a re-design of how it renders it as its probably a big enough refactor potentially.
Let me know your thoughts.
https://inindca.atlassian.net/browse/COMUI-2200
✅ Closes: COMUI-2200

fix(table-toolbar): fix initial glitchy render

---

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.scss
packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.tsx

fix(toggle): Add option to click on label

---

packages/genesys-spark-tokens/data/tokens.json
packages/genesys-spark-tokens/snapshot/css/gse-ui-formsAndInputs.css
packages/genesys-spark-tokens/snapshot/json/gse-ui-formsAndInputs.json
packages/genesys-spark-tokens/snapshot/less/gse-ui-formsAndInputs.less
packages/genesys-spark-tokens/snapshot/scss/_gse-ui-formsAndInputs.scss

✅ Closes: GDS-2312
New tokens added for datepicker component.

chore(datepicker): New tokens for datepicker

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss

chore(datepicker): Using new tokens on calendar icon on hover/focus

---

packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control-item/gux-segmented-control-item.tsx
packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/example.html
packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/tests/__snapshots__/gux-tooltip.spec.ts.snap
packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/tests/gux-tooltip.e2e.ts
packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/tests/gux-tooltip.spec.ts
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.scss
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.tsx
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/tests/__snapshots__/gux-copy-to-clipboard.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-ellipsis-button/gux-pagination-ellipsis-button.tsx
packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.tsx
packages/genesys-spark-components/src/components/stable/gux-tooltip-title/gux-tooltip-title.tsx
packages/genesys-spark-components/src/components/stable/gux-tooltip/example.html
packages/genesys-spark-components/src/components/stable/gux-tooltip/tests/__snapshots__/gux-tooltip.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-tooltip/tests/gux-tooltip.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-tooltip/tests/gux-tooltip.spec.ts
packages/genesys-spark-components/src/components/stable/gux-truncate/gux-truncate.tsx

Updating tooltip usage to use the named 'content' slot.

feat(tooltip): using the content slot

---

packages/genesys-spark-components/src/components/stable/gux-button/gux-button.scss

remove border-radius from inline buttons
✅ Closes: COMUI-2815

fix(button): remove border-radius from inline buttons

---

packages/genesys-spark-components/src/utils/decorator/on-click-outside.ts
packages/genesys-spark-components/src/utils/decorator/on-mutation.ts
packages/genesys-spark-components/src/utils/decorator/on-resize.ts

fixed memory leak in click outside decorator
COMUI-2823

fix(other): fixed memory leak in click outside decorator

---

packages/genesys-spark-components/src/genesys-spark-utils/get-closest-element.ts
packages/genesys-spark/src/utils/get-closest-element.ts

fix(other): fixed build error

---

packages/genesys-spark-tokens/data/tokens.json
packages/genesys-spark-tokens/snapshot/css/gse-ui-formControl.css
packages/genesys-spark-tokens/snapshot/json/gse-ui-formControl.json
packages/genesys-spark-tokens/snapshot/less/gse-ui-formControl.less
packages/genesys-spark-tokens/snapshot/scss/_gse-ui-formControl.scss

Adding token for label tooltip border radius

feat(tokens): Label icon tooltip border radius

---

packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-buttons.less

fix(pagination): Curtail expanding input on Firefox

---

packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/gux-pagination-buttons-legacy/gux-pagination-buttons-legacy.scss

fix(pagination-legacy): Curtail input from expanding on Firefox

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.tsx

Text in tooltip not showing currently. 
COMUI-2878

fix(form-field-range): Fix tooltip info

---

packages/genesys-spark-components/src/utils/decorator/on-click-outside.ts

popup now collapses when clicking another frame.
I think this issue should also be **backported.**
https://inindca.atlassian.net/browse/COMUI-2849
✅ Closes: COMUI-2849

fix(on-click-outside): popup now collapses when clicking another frame.

---

packages/genesys-spark-components/src/utils/decorator/on-click-outside.ts

popup now collapses when clicking another frame
COMUI-2849

fix(on-click-outside): popup now collapses when clicking another frame

---

packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/example.html

added localised examples
✅ Closes: COMUI-2884

docs(time-zone-picker): added localised examples

---

packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab-list/gux-tab-list.scss
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab/gux-tab.scss

vertical tab component now truncates
✅ Closes: COMUI-2882

fix(tabs): vertical tab component now truncates

---

package-lock.json
packages/genesys-spark-tokens/data-old/tokens.json
packages/genesys-spark-tokens/data/search_and_filter.json
packages/genesys-spark-tokens/package.json
packages/genesys-spark-tokens/snapshot/css/gse-ui-searchAndFilter.css
packages/genesys-spark-tokens/snapshot/css/gse-ui.css
packages/genesys-spark-tokens/snapshot/json/gse-core.json
packages/genesys-spark-tokens/snapshot/json/gse-semantic.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-actions.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-dataDisplay.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-feedback.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-formControl.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-formsAndInputs.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-layoutContainer.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-navigation.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-searchAndFilter.json
packages/genesys-spark-tokens/snapshot/json/gse-ui.json
packages/genesys-spark-tokens/snapshot/less/gse-ui-searchAndFilter.less
packages/genesys-spark-tokens/snapshot/less/gse-ui.less
packages/genesys-spark-tokens/snapshot/scss/_gse-ui-searchAndFilter.scss
packages/genesys-spark-tokens/snapshot/scss/_gse-ui.scss
packages/genesys-spark-tokens/utils/output-styles.mjs

updated token build tools
✅ Closes: COMUI-2907

refactor(other): updated token build tools

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/__snapshots__/gux-form-field-checkbox.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/tests/__snapshots__/gux-form-field-color.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/tests/__snapshots__/gux-form-field-number.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/tests/__snapshots__/gux-form-field-radio-group.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/tests/__snapshots__/gux-form-field-radio-group.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/tests/__snapshots__/gux-form-field-radio.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-search/tests/__snapshots__/gux-form-field-search.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-select/tests/__snapshots__/gux-form-field-select.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/tests/__snapshots__/gux-form-field-text-like.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-textarea/tests/__snapshots__/gux-form-field-textarea.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-zone-picker/tests/__snapshots__/gux-form-field-time-zone-picker.e2e.ts.snap

chore(other): updated snapshot tests

---

packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.less

addition of fixed height to calendar
COMUI-2915

fix(calendar): addition of fixed height to calendar

---

package-lock.json
packages/genesys-spark-chart-components/package.json
packages/genesys-spark-components-react/package.json

updated vega dependencies to latest
✅ Closes: ENGAGEUI-8566

chore(chart-column): updated vega dependencies to latest

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/gux-form-field-checkbox.tsx
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/__snapshots__/gux-form-field-checkbox.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/__snapshots__/gux-form-field-checkbox.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/tests/__snapshots__/gux-form-field-radio-group.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.tsx
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/tests/__snapshots__/gux-form-field-radio.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/tests/__snapshots__/gux-form-field-radio.spec.ts.snap

✅ Closes: COMUI-2925
Left aligning the help text and error text and icon for gux-form-field-checkbox and gux-form-field-radio components.

chore(form-field-checkbox): Left aligning help and error text

---

packages/genesys-spark-chart-components/src/test/axeConfig.ts
packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/tests/gux-time-zone-picker.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-content-search/tests/gux-content-search.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-datepicker/tests/gux-datepicker.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/tests/gux-dropdown-multi.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-dropdown/tests/gux-dropdown.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/tests/gux-form-field-radio-group.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/tests/gux-form-field-radio.e2e.ts
packages/genesys-spark-components/src/test/axeConfig.ts

Also added tickets to address the new violations relating to target size

test(other): add WCAG AA 2.2 to automated accessibility tests

---

packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.scss
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.tsx
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/tests/__snapshots__/gux-copy-to-clipboard.spec.ts.snap

fix status icon styles and align icon and text
[✅ Closes: COMUI-2965](https://inindca.atlassian.net/browse/COMUI-2965)

fix(copy-to-clipboard): fix status icon styles and align icon and text

---

packages/genesys-spark/src/index.ts

made register components options parameters optional
✅ Closes: made register components options parameters optional

fix(other): genesys-spark

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.tsx

Backport for https://github.com/MyPureCloud/genesys-spark/pull/538

fix(datepicker): ensure format is set before updating date

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/gux-form-field-color.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/gux-form-field-dropdown.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file/gux-form-field-file.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/gux-form-field-phone.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/gux-form-field-radio-group.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-search/gux-form-field-search.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-select/gux-form-field-select.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-textarea/gux-form-field-textarea.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/gux-form-field-time-picker.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-zone-picker/gux-form-field-time-zone-picker.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/gux-form-field.scss

Update the font-weight for form field labels

feat(other): Form field label font weight change

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.tsx

fix(form-field-range): Fix console error on updatePosition before componentWillLoad

---

packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-flyout-menu.scss
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-flyout-menu.tsx
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/tests/__snapshots__/gux-flyout-menu.spec.ts.snap

fix(flyout-menu): Fix menu arrow position

---

packages/genesys-spark-components/src/components/legacy/gux-advanced-dropdown-legacy/gux-advanced-dropdown.scss

fix(advanced-dropdown-legacy): Add focus ring

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox-group/gux-form-field-checkbox-group.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox-group/tests/gux-form-field-checkbox-group.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/gux-form-field-radio-group.scss

Address label related feedback from UX for `form-field-checkbox-group` and `form-field-radio-group` from comments on this ticket: https://inindca.atlassian.net/browse/COMUI-2785

fix(form-field-checkbox-group): update label style and disabled state

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/example.html
packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss

feat(datepicker): change font-weight on label

---

packages/genesys-spark-chart-components/src/components/beta/gux-visualization/gux-visualization.tsx

Closes [COMUI-2307](https://inindca.atlassian.net/browse/COMUI-2307)
[COMUI-2307]: https://inindca.atlassian.net/browse/COMUI-2307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: click events aren't triggering for line charts

---

packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss

fix heading token discrepancy
https://inindca.atlassian.net/browse/COMUI-3031
✅ Closes: COMUI-3031

fix(modal): fix heading token discrepancy

---

packages/genesys-spark-components/src/components/beta/gux-avatar-change-photo/gux-avatar-change-photo.tsx
packages/genesys-spark-components/src/components/beta/gux-avatar-change-photo/tests/__snapshots__/gux-avatar-change-photo.spec.ts.snap

This is just a small fix as the first part of COMUI-3041

feat(avatar): remove duplication in screenreader content for change photo version

---

packages/genesys-spark-tokens/data/$themes.json
packages/genesys-spark-tokens/data/semantic/global.json
packages/genesys-spark-tokens/data/semantic/theme/flare.json
packages/genesys-spark-tokens/data/ui/feedback.json
packages/genesys-spark-tokens/data/ui/forms_and_inputs.json
packages/genesys-spark-tokens/data/ui/unordered.json
packages/genesys-spark-tokens/snapshot-new/json/gse-flare-dark-semantic.json
packages/genesys-spark-tokens/snapshot-new/json/gse-flare-light-semantic.json
packages/genesys-spark-tokens/snapshot-new/json/gse-legacy-light-semantic.json
packages/genesys-spark-tokens/snapshot-new/scss/gse-flare-dark-core.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-flare-dark-semantic.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-flare-dark-ui.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-flare-light-core.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-flare-light-semantic.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-flare-light-ui.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-legacy-light-core.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-legacy-light-semantic.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-legacy-light-ui.scss
packages/genesys-spark-tokens/utils/create-themes.mjs

removed comments from generated tokens
✅ Closes: COMUI-3068

fix(other): removed comments from generated tokens

---

packages/genesys-spark-components/src/components/stable/gux-pagination/example.html
packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-ellipsis-button/gux-pagination-ellipsis-button.tsx

fix(pagination): Ellipsis button translation

---

package-lock.json
package.json
packages/genesys-spark-chart-components-react/package.json
packages/genesys-spark-chart-components/package.json
packages/genesys-spark-components-react/package.json
packages/genesys-spark-components/package.json
packages/genesys-spark-tokens/package.json
packages/genesys-spark/package.json
shared-configs/eslint-config-genesys-spark-components/package.json
shared-configs/prettier-config-genesys-spark-components/package.json
shared-configs/stylelint-config-genesys-spark-components/package.json
web-apps/genesys-spark-examples/package.json

updated some dependencies to latest
✅ Closes: COMUI-2775

chore(other): updated some dependencies to latest

---

packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/gux-pagination-items-per-page-legacy/tests/__snapshots__/gux-pagination-items-per-page.spec.ts.snap
packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/tests/__snapshots__/gux-pagination.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-dropdown/example.html
packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx
packages/genesys-spark-components/src/components/stable/gux-dropdown/tests/__snapshots__/gux-dropdown.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/tests/__snapshots__/gux-pagination-items-per-page.spec.ts.snap

feat(dropdown): Support mixed RTL / LTR content

---

packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-button.service.ts

fix(pagination): Remove last page duplication on simple layout

---

packages/genesys-spark-components/src/components/beta/gux-cta-group/readme.md
packages/genesys-spark-components/src/components/stable/gux-toast/gux-toast.scss
packages/genesys-spark-components/src/components/stable/gux-toast/gux-toast.tsx
packages/genesys-spark-components/src/components/stable/gux-toast/readme.md
packages/genesys-spark-components/src/components/stable/gux-toast/tests/__snapshots__/gux-toast.spec.ts.snap

Closes [COMUI-3082](https://inindca.atlassian.net/browse/COMUI-3082)
[COMUI-3082]: https://inindca.atlassian.net/browse/COMUI-3082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(toast): updating to use gux-cta-group

---

packages/genesys-spark-components/src/components/legacy/gux-modal-legacy/gux-modal-legacy.scss

✅ Closes: COMUI-3103
Very similar to [this earlier change](https://github.com/MyPureCloud/genesys-spark/pull/358)

fix(modal-legacy): prevent focus ring cropping

---

packages/genesys-spark-components/src/components/stable/gux-accordion/gux-accordion-section/gux-accordion-section.scss

fix(accordion): arrow not centered

---

docs/intl.md
packages/genesys-spark-components/src/genesys-spark-utils/intl.ts
packages/genesys-spark/src/utils/intl.ts

looking for feedback from the team

docs(other): add docs for intl

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.tsx

fix(form-field-range): prevent error when resized before render

---

packages/genesys-spark-components/src/components/beta/gux-tooltip-base/gux-tooltip-base.scss
packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.scss

chore(tooltip): speed up animation

---

packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.less

chore(tooltip): speed up animation delay

---

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.scss

chore(toggle): Center toggle label against switch

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/example.html
packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss

This will allow you to set a width on the datepicker with CSS and will stretch the input to that size.

feat(datepicker): allow a width to be applied to the datepicker input

---

packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss

chore(modal): Allow medium and large modals to contract on smaller screens

---

packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control-item/gux-segmented-control-item.scss

vertically center icons and text
[✅ Closes: COMUI-3146](https://inindca.atlassian.net/browse/COMUI-3146)

fix(segmented-control): vertically center icons and text

---

package-lock.json
packages/genesys-spark-components/package.json
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-menu/gux-submenu/gux-submenu.tsx

added flip to sub-menu
✅ Closes: COMUI-3099

fix(flyout-menu): added flip to sub-menu

---

packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar.service.ts
packages/genesys-spark-components/src/components/beta/gux-table-toolbar/gux-table-toolbar.tsx

fix console errors when slots are absent
[COMUI-3148](https://inindca.atlassian.net/browse/COMUI-3148)
[COMUI-3148]: https://inindca.atlassian.net/browse/COMUI-3148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(toolbar) - fix console errors when slots are absent 

---

packages/genesys-spark/src/index.ts

now using themeable tokens
✅ Closes: COMUI-3141

feat(other): now using themeable tokens

---

packages/genesys-spark-tokens/data/$themes.json
packages/genesys-spark-tokens/data/ui/unordered.json
packages/genesys-spark-tokens/reports/missing-old-tokens.json
packages/genesys-spark-tokens/reports/used-tokens.json
packages/genesys-spark-tokens/snapshot-new/json/gse-flare-dark-ui.json
packages/genesys-spark-tokens/snapshot-new/json/gse-flare-light-ui.json
packages/genesys-spark-tokens/snapshot-new/json/gse-legacy-light-ui.json
packages/genesys-spark-tokens/snapshot-new/scss/gse-flare-dark-ui.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-flare-light-ui.scss
packages/genesys-spark-tokens/snapshot-new/scss/gse-legacy-light-ui.scss

tokens update
✅ Closes: COMUI-3172

refactor(other): tokens update

---

packages/genesys-spark-components/src/components/stable/gux-popover-list/gux-popover-list.scss
packages/genesys-spark-components/src/components/stable/gux-popover-list/gux-popover-list.tsx

**Note**
See ticket for more details of issues
https://floating-ui.com/docs/computeposition#strategy
https://floating-ui.com/docs/misc#clipping
[✅ Closes: COMUI-3161](https://inindca.atlassian.net/browse/COMUI-3161)

fix(popover-list): change strategy to fixed

---

packages/genesys-spark-chart-components/src/test/e2eTestUtils.ts
packages/genesys-spark-components/src/test/e2eTestUtils.ts

chore(other): fix axe type

---

packages/genesys-spark-components/src/components/stable/gux-form-field/helper-components/gux-form-field-input-clear-button/gux-form-field-input-clear-button.scss

Fix styling of clearable button.
[✅ Closes: COMUI-3179](https://inindca.atlassian.net/browse/COMUI-3179)

fix(other): form-field-input-clear-button fix styling

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss

remove background color on input
[✅ Closes: COMUI-3180](https://inindca.atlassian.net/browse/COMUI-3180)

fix(datepicker): remove background color on input

---

packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.scss
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.tsx
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/tests/__snapshots__/gux-copy-to-clipboard.spec.ts.snap

fixed styles
✅ Closes: COMUI-3174

fix(copy-to-clipboard): fixed styles

---

packages/genesys-spark-components/src/components/beta/gux-form/gux-form-heading/gux-form-heading.scss
packages/genesys-spark-components/src/components/beta/gux-form/gux-form.light.scss

apply `heading-lg` instead of `body-lg`
[✅ Closes: COMUI-3182](https://inindca.atlassian.net/browse/COMUI-3182)

fix(form): fix form-heading styles

---

packages/genesys-spark-components/src/components/beta/gux-selector-cards/example.html
packages/genesys-spark-components/src/components/beta/gux-selector-cards/gux-selector-card/example.html
packages/genesys-spark-components/src/components/beta/gux-selector-cards/gux-selector-card/gux-selector-card.scss
packages/genesys-spark-components/src/components/stable/gux-badge/gux-badge.scss

https://inindca.atlassian.net/browse/COMUI-3185

feat(selector-cards) - UX review fixes

---

packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-menu/gux-menu-option/gux-menu-option.scss
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-menu/gux-submenu/gux-submenu.scss

apply box-sizing to flyout menu options
[✅ Closes: COMUI-3186](https://inindca.atlassian.net/browse/COMUI-3186)

fix(flyout-menu): apply box-sizing to flyout menu options

---

packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar-focusable/__snapshots__/gux-avatar-focusable.e2e.ts.snap
packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar-focusable/gux-avatar-focusable.light.scss
packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar-focusable/gux-avatar-focusable.tsx
packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar-focusable/tests/__snapshots__/gux-avatar-focusable.e2e.ts.snap
packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar-focusable/tests/__snapshots__/gux-avatar-focusable.spec.ts.snap
packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar-focusable/tests/gux-avatar-focusable.e2e.ts

feat(avatar): use the same focus ring on small avatars

---

packages/genesys-spark-components/src/components/beta/gux-popover-beta/gux-popover.scss
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor-action-group/gux-rich-text-editor-action-group.scss
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor.light.scss

linted recent code commits
✅ Closes: COMUI-3207

chore(other): linted recent code commits

---

packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/example.html
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor-action/gux-rich-text-editor-action.types.ts
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor-action/i18n/en.json
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor-action/readme.md
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor.service.ts
packages/genesys-spark-components/src/i18n/translations/en.json

Fix broken e2e tests
Changed `bulletedList` to be `bulletList` to sync with tiptap.
✅ Closes: COMUI-3228

fix(rich-text-editor): fix broken e2e tests

---

packages/genesys-spark-components/.stylelintrc.json
packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.light.scss
packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.scss
packages/genesys-spark-components/src/components/stable/gux-badge/gux-badge.scss
packages/genesys-spark-components/src/components/stable/gux-blank-state/gux-blank-state.scss
packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.light.scss
packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.scss
packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.scss
packages/genesys-spark-components/src/components/stable/gux-card/gux-card.scss
packages/genesys-spark-components/src/components/stable/gux-column-manager/gux-column-manager.scss
packages/genesys-spark-components/src/components/stable/gux-content-search/gux-content-search.scss
packages/genesys-spark-components/src/components/stable/gux-context-menu/gux-context-menu.scss
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.scss
packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss
packages/genesys-spark-components/src/components/stable/gux-dismiss-button/gux-dismiss-button.scss
packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.scss
packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.scss
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-flyout-menu.scss
packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.scss
packages/genesys-spark-components/src/components/stable/gux-inline-alert/gux-inline-alert.scss
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.scss
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.scss
packages/genesys-spark-components/src/components/stable/gux-loading-message/gux-loading-message.scss
packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss

Using logical properties in scss of first half of stable components. Second half to follow .
✅ Closes: COMUI-3198

chore(other): logical properties for stable components pt1

---

packages/genesys-spark-components/src/components/beta/gux-selector-cards/gux-selector-card/gux-selector-card.scss

feat(selector-cards): stretch height

---

packages/genesys-spark-components/src/components/beta/gux-form/gux-form-footer/readme.md
packages/genesys-spark-components/src/components/stable/gux-table/gux-row-select/gux-row-select.scss
packages/genesys-spark-components/src/components/stable/gux-table/gux-row-select/gux-row-select.tsx

added safari repaint bug workaround
✅ Closes: COMUI-2582

fix(table): added safari repaint bug workaround

---

packages/genesys-spark-chart-components/src/components/beta/gux-visualization/example.html

✅ Closes: [ENGAGEUI-8201]
[ENGAGEUI-8201]: https://inindca.atlassian.net/browse/ENGAGEUI-8201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(visualization): add spark examples for line charts

---

packages/genesys-spark-components/src/components/beta/gux-popover-beta/gux-popover.scss
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor-action-group/gux-rich-text-editor-action-group.scss
packages/genesys-spark-components/src/components/beta/gux-segmented-control/example.html
packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control-item/gux-segmented-control-item.scss
packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control-item/gux-segmented-control-item.tsx
packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control-item/gux-segmented-control-item.types.ts
packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control.tsx

added disabled state
✅ Closes: COMUI-3009

feat(segmented-control): added disabled state

---

packages/genesys-spark-components/src/components/stable/gux-table/gux-table.light.scss

Closes [COMUI-3201](https://inindca.atlassian.net/browse/COMUI-3201)
[COMUI-3201]: https://inindca.atlassian.net/browse/COMUI-3201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(table): header showing above popups

---

packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi-tag/gux-dropdown-multi-tag.tsx

feat(dropdown-multi): block tag from expanding listbox when removed

---

packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option-icon/gux-option-icon.scss

fix option-icon alignment
✅ Closes: [COMUI-3231](https://inindca.atlassian.net/browse/COMUI-3231)
[COMUI-3231]: https://inindca.atlassian.net/browse/COMUI-3231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): fix option-icon alignment

---

packages/genesys-spark-components/src/components/stable/gux-table/gux-table.light.scss

Closes [COMUI-1652](https://inindca.atlassian.net/browse/COMUI-1652)
[COMUI-1652]: https://inindca.atlassian.net/browse/COMUI-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(table): removing workarounds for has selector

---

packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/example.html
packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/gux-popover-list.scss
packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/gux-popover-list.tsx
packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/readme.md
packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/tests/__snapshots__/gux-popover-list.spec.ts.snap
packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/tests/gux-popover-list.e2e.ts
packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/tests/gux-popover-list.spec.ts
packages/genesys-spark-components/src/components/stable/gux-dismiss-button/readme.md

✅ Closes: COMUI-3184
There is a separate ticket to get the arrow to show: COMUI-3210

chore(popover-list-beta): Added popover-list-beta component

---

packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/example.html
packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.tsx

fixed accessibility warning
✅ Closes: COMUI-3241

fix(button-multi): fixed accessibility warning

---

packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor.light.scss

add missing padding to code block
✅ Closes: COMUI-2982

style(rich-text-editor): ux qa

---

packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.tsx

fixed accessibility warning
✅ Closes: COMUI-3197

fix(action-button): fixed accessibility warning

---

packages/genesys-spark-chart-components/src/components/beta/gux-visualization/example.html

✅ Closes: [ENGAGEUI-8704][ENGAGEUI-8703]
[ENGAGEUI-8704]: https://inindca.atlassian.net/browse/ENGAGEUI-8704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(visualization): add spark donut and pie chart examples

---

packages/genesys-spark-components/src/components/stable/gux-toast/tests/__snapshots__/gux-toast.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-toast/tests/gux-toast.spec.ts
web-apps/genesys-spark-examples/src/component-viewer/panels/events.js
web-apps/genesys-spark-examples/src/styles/component-viewer.scss

removed usage of legacy toast from examples doc
✅ Closes: COMUI-3276

refactor(toast): removed usage of legacy toast from examples doc

---

packages/genesys-spark-components/src/components/stable/gux-pagination/a11yManualChecklist.md

Closes [COMUI-3272](https://inindca.atlassian.net/browse/COMUI-3272)
[COMUI-3272]: https://inindca.atlassian.net/browse/COMUI-3272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(pagination): manual a11y check

---

packages/genesys-spark-components/src/components/stable/gux-button-multi/a11yManualChecklist.md

check manual a11y for button multi
✅ Closes: COMUI-3269

chore(button-multi): check manual a11y

---

packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/a11yManualChecklist.md
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.tsx
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/i18n/en.json
packages/genesys-spark-components/src/i18n/translations/en.json

updated accessibility log
✅ Closes: COMUI-3271

chore(copy-to-clipboard): updated accessibility log

---

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.scss

remove unused hex values
✅ Closes: COMUI-3308

fix(toggle): remove unused hex values

---

packages/genesys-spark-components/src/components/beta/gux-calendar-beta/components/single/gux-calendar.scss
packages/genesys-spark-components/src/components/beta/gux-calendar-beta/components/single/gux-calendar.tsx
packages/genesys-spark-components/src/components/beta/gux-calendar-beta/tests/__snapshots__/gux-calendar.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.scss
packages/genesys-spark/src/style/_focus.scss

style changes in preparation for dark mode
✅ Closes: COMUI-3294

fix(calendar): style changes in preparation for dark mode

---

packages/genesys-spark-chart-components/src/components/beta/gux-visualization/example.html

add bar chart target line example and move target lines to top layer
✅ Closes: ENGAGEUI-8709

docs(visualization): add bar chart target line example

---

packages/genesys-spark-components/src/components/stable/gux-rating/a11yManualChecklist.md
packages/genesys-spark-components/src/components/stable/gux-rating/gux-rating.tsx

Can now increment the value using left and right arrows
Updating component a11y checklist

feat(rating): can now increment the value using left and right arrows

---

package-lock.json
packages/genesys-spark-chart-components/package.json

chore(other): update vega dependencies

---

packages/genesys-spark-components/src/components/stable/gux-breadcrumbs/a11yManualChecklist.md

update a11y manual checklist
✅ Closes: COMUI-3317

chore(breadcrumbs): update a11y manual checklist

---

package-lock.json
packages/genesys-spark-components/package.json

chore(other): update sortablejs to latest

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/gux-form-field-number.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/gux-form-field-text-like.scss
packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.scss

COMUI-3298, COMUI-3296 & COMUI-3299

chore(form-field-text-like): add populated color to scss

---

packages/genesys-spark-components/src/components/stable/gux-inline-alert/a11yManualChecklist.md

update a11y manual checklist
[✅ Closes: COMUI-3329](https://inindca.atlassian.net/browse/COMUI-3329)

chore(inline-alert): update a11y manual checklist

---

packages/genesys-spark-components/src/components/stable/gux-tag/gux-tag.scss

remove hex values
[✅ Closes: COMUI-3307](https://inindca.atlassian.net/browse/COMUI-3307)

chore(tag): remove hex values

---

packages/genesys-spark-components/src/components/stable/gux-dismiss-button/a11yManualChecklist.md

Closes [COMUI-3324](https://inindca.atlassian.net/browse/COMUI-3324)
[COMUI-3324]: https://inindca.atlassian.net/browse/COMUI-3324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(dismiss-button): update a11y manual checklist

---

packages/genesys-spark-components/src/components/stable/gux-text-highlight/a11yManualChecklist.md

update a11y check manual
✅ Closes: COMUI-3344

chore(text-highlight): update a11y check manual

---

packages/genesys-spark-components/src/components/stable/gux-content-search/a11yManualChecklist.md

update a11y manual check
✅ Closes: COMUI-3322

chore(content-search): update a11y manual check

---

package-lock.json
packages/genesys-spark-components/src/components/stable/gux-button-slot/readme.md
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab-list/readme.md
web-apps/genesys-spark-examples/package.json

chore(other): update parse5 to latest

---

packages/genesys-spark-components/src/components/stable/gux-loading-message/a11yManualChecklist.md
packages/genesys-spark-components/src/components/stable/gux-page-loading-spinner/a11yManualChecklist.md
packages/genesys-spark-components/src/components/stable/gux-radial-progress/a11yManualChecklist.md

updated a11y checklists
✅ Closes: COMUI-3331 COMUI-3333 COMUI-3336 COMUI-3337

chore(radial-loading): updated a11y checklists

---

packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor-action-group/gux-rich-text-editor-action-group.scss

chore(rich-text-editor): add token

---

packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.tsx
packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-list/gux-list-item/gux-list-item.scss
packages/genesys-spark-components/src/components/stable/gux-list/list-item-default.scss
packages/genesys-spark-components/src/components/stable/gux-table/gux-table.light.scss

component now delegates focus
✅ Closes: COMUI-3362

fix(button-multi): component now delegates focus

---

packages/genesys-spark-components/src/components/stable/gux-icon/a11yManualChecklist.md
packages/genesys-spark/src/hosts.ts

chore(icon): accessibility checklist

---

packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/a11yManualChecklist.md

a11y manual testing check
[✅ Closes: COMUI-3335](https://inindca.atlassian.net/browse/COMUI-3335)

chore(popover-list-beta): a11y manual testing check

---

packages/genesys-spark-components/src/components/stable/gux-toggle/example.html
packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.tsx
packages/genesys-spark-components/src/components/stable/gux-toggle/readme.md
packages/genesys-spark-components/src/components/stable/gux-toggle/tests/__snapshots__/gux-toggle.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-toggle/tests/__snapshots__/gux-toggle.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-toggle/tests/gux-toggle.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-toggle/tests/gux-toggle.spec.ts

backport of https://github.com/MyPureCloud/genesys-spark/pull/808/files

fix(gux-toggle): a11y add support for single label

---

packages/genesys-spark-components/scripts/check-a11y.mjs
packages/genesys-spark-components/src/components/stable/gux-popover/a11yManualChecklist.md

manual a11y-check
[✅ Closes: COMUI-3334](https://inindca.atlassian.net/browse/COMUI-3334)

chore(popover): manual a11y-check

---

packages/genesys-spark-components/scripts/check-a11y.mjs
packages/genesys-spark-components/src/components/stable/gux-table-toolbar/a11yManualChecklist.md

manual check-a11y
[✅ Closes: COMUI-3340](https://inindca.atlassian.net/browse/COMUI-3340)

chore(table-toolbar): manual check-a11y

---

packages/genesys-spark-components/src/components/stable/gux-tabs/a11yManualChecklist.md

Closes [COMUI-3341](https://inindca.atlassian.net/browse/COMUI-3341)
[COMUI-3341]: https://inindca.atlassian.net/browse/COMUI-3341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(tabs): update a11y manual checklist

---

packages/genesys-spark-components/scripts/check-a11y.mjs
packages/genesys-spark-components/src/components/stable/gux-table/a11yManualChecklist.md
packages/genesys-spark-components/src/components/stable/gux-table/tests/gux-table.e2e.ts

accessibility review
✅ Closes: COMUI-3339

chore(table): accessibility review

---

packages/genesys-spark-components/src/components/stable/gux-flyout-menu/a11yManualChecklist.md

chore(flyout-menu): accessibility checklist

---

packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/a11yManualChecklist.md

Closes [COMUI-3342](https://inindca.atlassian.net/browse/COMUI-3342)
[COMUI-3342]: https://inindca.atlassian.net/browse/COMUI-3342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(tabs-advanced): update a11y manual checklist

---

packages/genesys-spark-components/src/components/stable/gux-button/gux-button.tsx
packages/genesys-spark-components/src/components/stable/gux-modal/example.html

added autofocus property
✅ Closes: COMUI-3379

feat(button): added autofocus property

---

packages/genesys-spark-components/src/components/stable/gux-dropdown/example.html
packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.scss
packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option-icon/gux-option-icon.scss
packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option-icon/gux-option-icon.tsx

option icon position added
✅ Closes: COMUI-3355

feat(dropdown): option icon position added

---

package-lock.json
packages/genesys-spark-components/package.json
packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/tests/__snapshots__/gux-time-zone-picker.spec.ts.snap

update @vvo/tzdb and google-libphonenumber dependencies to latest

chore(other): update some dependencies to latest

---

packages/genesys-spark-components/src/components/stable/gux-tooltip/a11yManualChecklist.md

Closes [COMUI-3348](https://inindca.atlassian.net/browse/COMUI-3348)
[COMUI-3348]: https://inindca.atlassian.net/browse/COMUI-3348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(tooltip): update a11y manual checklist

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/a11yManualChecklist.md

chore(form-field-color): a11y checklist

---

packages/genesys-spark-components/src/components/stable/gux-modal/a11yManualChecklist.md

Closes [COMUI-3332](https://inindca.atlassian.net/browse/COMUI-3332)
[COMUI-3332]: https://inindca.atlassian.net/browse/COMUI-3332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(modal): add a11y manual checklist

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/a11yManualChecklist.md

Ticket to resolve the failure:
https://inindca.atlassian.net/browse/COMUI-3412

chore(form-field-dropdown): a11y checklist

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/a11yManualChecklist.md

Ticket to fix: https://inindca.atlassian.net/browse/COMUI-3415

chore(form-field-phone): a11y check

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-select/a11yManualChecklist.md

chore(form-field-select): accessibility checklist

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-zone-picker/a11yManualChecklist.md

chore(form-field-time-zone-picker): accessibility checklist

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.light.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.scss

Cleaning up some css that was changed based on the new tokens from [COMUI-3356](https://inindca.atlassian.net/browse/COMUI-3356)
[COMUI-3356]: https://inindca.atlassian.net/browse/COMUI-3356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(form-field-range): refactoring some css

---

packages/genesys-spark-components/src/components/stable/gux-form-field/functional-components/gux-form-field-error/gux-form-field-error.scss

Closes [COMUI-3389](https://inindca.atlassian.net/browse/COMUI-3389)
[COMUI-3389]: https://inindca.atlassian.net/browse/COMUI-3389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(form-field-error): aligning error icon with top row of error message

---

packages/genesys-spark-tokens/data/$themes.json

Reorganize figma styles, didn't add new tokens

feat(tokens): Reorganize figma styles

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/a11yManualChecklist.md

chore(form-field-range): update accessibilty manual checklist 

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/a11yManualChecklist.md

chore(datepicker): Manual accessibility checklist

---

packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.scss

hide horizontal scrollbar
[✅ Closes: COMUI-3376](https://inindca.atlassian.net/browse/COMUI-3376)

fix(listbox-multi): hide horizontal scrollbar

---

packages/genesys-spark-components/src/components/stable/gux-button-multi/a11yManualChecklist.md
packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.tsx

fix(button-multi): Fixed keyboard accessibility

---

packages/genesys-spark-components/src/components/stable/gux-dismiss-button/gux-dismiss-button.scss

fixed small size css
✅ Closes: COMUI-3353

fix(dismiss-button): fixed small size css

---

packages/genesys-spark-components/src/components/beta/gux-tooltip-base/gux-tooltip-base.scss
packages/genesys-spark-components/src/components/beta/gux-tooltip-base/gux-tooltip-base.tsx
packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.scss
packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.tsx

improved accessibility
✅ Closes: COMUI-3420

fix(tooltip): improved accessibility

---

packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.tsx

added img role to svg
✅ Closes: COMUI-3359

fix(icon): added img role to svg

---

packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab-list/gux-tab-list.tsx
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab/gux-tab.tsx
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab/tests/__snapshots__/gux-tab.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab/tests/gux-tab.spec.ts
packages/genesys-spark-components/src/components/stable/gux-tabs/tests/__snapshots__/gux-tabs.spec.ts.snap

Removing the ability to focus on a disabled tab.

feat(tabs): disabled tab is not focusable

---

packages/genesys-spark-components/src/components/beta/gux-avatar/a11yManualChecklist.md

Closes [COMUI-3466](https://inindca.atlassian.net/browse/COMUI-3466)
[COMUI-3466]: https://inindca.atlassian.net/browse/COMUI-3466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(avatar-beta): manual accessibility checklist

---

packages/genesys-spark-components/src/components/stable/gux-tag/a11yManualChecklist.md
packages/genesys-spark-components/src/components/stable/gux-tag/gux-tag.scss

Closes [COMUI-3350](https://inindca.atlassian.net/browse/COMUI-3350)
[COMUI-3350]: https://inindca.atlassian.net/browse/COMUI-3350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(tag): increasing outline-offset to fix accessibility issue with color

---

packages/genesys-spark-components/src/components/beta/gux-date/a11yManualChecklist.md
packages/genesys-spark-components/src/components/beta/gux-time/a11yManualChecklist.md

completed accesibility check
✅ Closes: COMUI-3470

docs(date-beta): completed accesibility check

---

packages/genesys-spark-components/src/components/beta/gux-date-time/a11yManualChecklist.md

docs(date-time-beta): check a11y list

---

packages/genesys-spark-components/src/components/beta/gux-announce/a11yManualChecklist.md

chore(announce-beta): a11y checklist

---

packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/a11yManualChecklist.md

update manual a11y checklist
✅ Closes: COMUI-3481

chore(rich-text-editor-beta): update manual a11y checklist

---

packages/genesys-spark-components/src/components/beta/gux-selector-cards/a11yManualChecklist.md

update manual a11y checklist
✅ Closes: COMUI-3484

chore(selector-cards-beta): update manual a11y checklist

---

packages/genesys-spark-components/src/components/beta/gux-cta-group/a11yManualChecklist.md

chore(cta-group): Manual accessibility markdown file update

---

packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/a11yManualChecklist.md

chore(popover-list-beta): Updated accessibility markdown file

---

packages/genesys-spark-components/src/components/beta/gux-label-info/a11yManualChecklist.md
packages/genesys-spark-components/src/components/beta/gux-label-info/example.html

Closes [COMUI-3475](https://inindca.atlassian.net/browse/COMUI-3475)
[COMUI-3475]: https://inindca.atlassian.net/browse/COMUI-3475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(label-info-beta): manual accessibility checklist, add form field example

---

packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss

fixed backgroud color token
✅ Closes: COMUI-3300

fix(modal): fixed backgroud color token

---

packages/genesys-spark-components/src/components/beta/gux-time-zone/a11yManualChecklist.md

chore(time-zone-beta): Added manual accessibility markdown file

---

packages/genesys-spark-components/src/components/beta/gux-popover-beta/a11yManualChecklist.md

chore(popover-beta): Added manual accessibility checklist

---

packages/genesys-spark-components/src/components/stable/gux-blank-state/gux-blank-state.tsx

fix(blank-state): hide guidance when not provided

---

packages/genesys-spark-components/src/components/beta/gux-screen-reader/a11yManualChecklist.md

chore(screen-reader-beta): accessibility checklist

---

packages/genesys-spark-components/src/components/beta/gux-icon-tooltip/a11yManualChecklist.md

chore(icon-tooltip-beta): accessibility checklist

---

packages/genesys-spark-components/src/components/beta/gux-phone-input/a11yManualChecklist.md

Closes [COMUI-3478](https://inindca.atlassian.net/browse/COMUI-3478)
[COMUI-3478]: https://inindca.atlassian.net/browse/COMUI-3478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(phone-input-beta): manual accessibility checklist

---

packages/genesys-spark-components/src/components/beta/gux-month-picker/a11yManualChecklist.md

chore(month-picker-beta): Added manual accessibility markdown file

---

packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.scss
packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/tests/__snapshots__/gux-dropdown-multi.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/tests/gux-dropdown-multi.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap

Reverting combobox & adding test to catch the failure.
Ticket to revisit the issue: https://inindca.atlassian.net/browse/COMUI-2948

feat(dropdown-multi): reverting combobox change

---

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.scss
packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.tsx

changed toggle error icon
✅ Closes: COMUI-3506

fix(toggle): changed toggle error icon

---

packages/genesys-spark-components/src/components/beta/gux-segmented-control/a11yManualChecklist.md

chore(segmented-control-beta): accessibility checklist

---

packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tab/gux-tab.scss

Closes [COMUI-3411](https://inindca.atlassian.net/browse/COMUI-3411)
[COMUI-3411]: https://inindca.atlassian.net/browse/COMUI-3411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(tab): focus ring cut off on bottom

---

packages/genesys-spark-components/src/components/beta/gux-calendar-beta/a11yManualChecklist.md
packages/genesys-spark-components/src/components/beta/gux-popover-beta/readme.md

Closes [COMUI-3468](https://inindca.atlassian.net/browse/COMUI-3468)
[COMUI-3468]: https://inindca.atlassian.net/browse/COMUI-3468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(calendar-beta): manual accessibility checklist

---

packages/genesys-spark-components/src/components/beta/gux-popover-beta/gux-popover.scss
packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.scss

removed min width
✅ Closes: COMUI-3531

fix(popover): removed min width

---

packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.service.ts
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.tsx

Closes [COMUI-3516](https://inindca.atlassian.net/browse/COMUI-3516)
[COMUI-3516]: https://inindca.atlassian.net/browse/COMUI-3516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown-multi): fixing issue when user sets value to empty string

---

packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/a11yManualChecklist.md

chore(tooltip-beta): Updated manual accessibility markdown file

---

packages/genesys-spark-components/src/components/stable/gux-context-menu/gux-context-menu.tsx
packages/genesys-spark-components/src/components/stable/gux-context-menu/readme.md
packages/genesys-spark-components/src/components/stable/gux-context-menu/tests/__snapshots__/gux-context-menu.spec.ts.snap

added placement option of popup menu
✅ Closes: COMUI-3242

feat(context-menu): added placement option of popup menu

---

packages/genesys-spark-chart-components/src/genesys-spark-utils/intl.ts
packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-list/gux-month-list-item/readme.md
packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/readme.md
packages/genesys-spark-components/src/components/beta/gux-month-picker/readme.md
packages/genesys-spark-components/src/components/beta/gux-time-zone/gux-time-zone.tsx
packages/genesys-spark-components/src/components/stable/gux-time-picker/readme.md
packages/genesys-spark-components/src/genesys-spark-utils/intl.ts

fix(time-zone-beta): fix translations

---

packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss

remove the background color from the label
[✅ Closes: COMUI-3559](https://inindca.atlassian.net/browse/COMUI-3559)

fix(datepicker): background-color should not include label

---

packages/genesys-spark-components/src/components/beta/gux-popover-beta/gux-popover.tsx
packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.tsx

dismiss button moved out of title element
✅ Closes: COMUI-3548

fix(popover): dismiss button moved out of title element

---

package-lock.json
packages/genesys-spark-chart-components-react/package.json
packages/genesys-spark-chart-components/package.json
packages/genesys-spark-components-react/package.json
packages/genesys-spark-components/package.json
packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/tests/__snapshots__/gux-tabs-advanced.spec.ts.snap
packages/genesys-spark/package.json
shared-configs/eslint-config-genesys-spark-components/package.json
web-apps/genesys-spark-examples/package.json

chore(other): update stencil to v4.23

---

packages/genesys-spark-components/src/genesys-spark-utils/intl.ts
packages/genesys-spark-components/src/test/intl.spec.ts
packages/genesys-spark/src/utils/intl.ts

backport of https://github.com/MyPureCloud/genesys-spark/pull/983

fix(other): update localization logic to treat en-us dom lang as en

---

packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx

fix(dropdown): Remove subtext from selected gux-option-icon text

---

packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.tsx
packages/genesys-spark-components/src/components/stable/gux-time-picker/tests/__snapshots__/gux-time-picker.spec.ts.snap

✅ Closes: COMUI-3410
This PR came out of this other one. I was having trouble after merging main into that PR's branch so I created a fresh branch and PR
Old PR: https://github.com/MyPureCloud/genesys-spark/pull/999

chore(time-picker): Added aria spinbutton role

---

packages/genesys-spark-components/src/components/beta/gux-calendar-beta/gux-calendar.scss

fixed token reference
✅ Closes: COMUI-3620

fix(calendar-beta): fixed token reference

---

packages/genesys-spark-components/src/components/stable/gux-list/example.html

fixed example page dark mode appearance
✅ Closes: COMUI-3617

fix(list): fixed example page dark mode appearance

---

packages/genesys-spark-components/src/components/stable/gux-radial-loading/gux-radial-loading.functional.scss

fixed dark mode appearance
✅ Closes: COMUI-3615

fix(radial-loading): fixed dark mode appearance

---

packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar.scss

fixed presence icons in dark mode
✅ Closes: COMUI-3628

fix(avatar-beta): fixed presence icons in dark mode

---

packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/example.html
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor-beta.tsx
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor.scss

container now inherits size from host
[✅ Closes: COMUI-3568](https://inindca.atlassian.net/browse/COMUI-3568)

fix(rich-text-editor-beta): container now inherits size from host

---

packages/genesys-spark-components/src/components/beta/gux-popover-beta/gux-popover.tsx
packages/genesys-spark-components/src/components/beta/gux-popover-beta/readme.md

Open to opinions on this change and also if approved do we think we should apply this to the stable component also or just have it as a beta feature ?
✅ Closes: COMUI-3552

fix(popover-beta): add method to close popover

---

packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx

chore(dropdown): Focus listbox option on enter or space key press

---

package-lock.json
packages/genesys-spark-chart-components/tsconfig.json
packages/genesys-spark-components-react/tsconfig.json
packages/genesys-spark-components/package.json
packages/genesys-spark-components/scripts/wrap-stencil.js
packages/genesys-spark-components/tsconfig.json

update @js-temporal/polyfill dependency to latest

chore(other): update @js-temporal/polyfill dependency to latest

---

packages/genesys-spark-components/src/components/legacy/gux-disclosure-button-legacy/gux-disclosure-button.scss
packages/genesys-spark-components/src/components/legacy/gux-modal-legacy/gux-modal-legacy.scss
packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/gux-pagination-buttons-legacy/gux-pagination-buttons-legacy.scss
packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/gux-pagination-item-counts-legacy/gux-pagination-item-counts-legacy.scss
packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/gux-pagination-items-per-page-legacy/gux-pagination-items-per-page-legacy.scss
packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/gux-pagination-legacy.scss

use scss variables in legacy components
✅ Closes: COMUI-3647

refactor(other): use scss variables in legacy components

---

packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx

fix(dropdown): subtext included in selected option

---

packages/genesys-spark-components/src/components/legacy/gux-action-toast-legacy/gux-action-toast.light.scss
packages/genesys-spark-components/src/components/legacy/gux-action-toast-legacy/gux-action-toast.scss
packages/genesys-spark-components/src/components/legacy/gux-notification-toast-legacy/gux-notification-toast.scss
packages/genesys-spark-components/src/components/legacy/gux-simple-toast-legacy/gux-simple-toast.scss
packages/genesys-spark-components/src/components/legacy/gux-switch-legacy/gux-switch-item/gux-switch-item.scss
packages/genesys-spark-tokens/reports/used-tokens.json

improved legacy components dark mode implementation
✅ Closes: COMUI-3633

fix(other): improved legacy components dark mode implementation

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file-beta/components/gux-file-list-item/gux-file-list-item.scss
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file-beta/example.html

small UX fixes
✅ Closes: COMUI-3129

fix(form-field-file-beta): small UX fixes

---

docs/dark-mode.md

Added official dark mode support

feat(other): Added official dark mode support

---

packages/genesys-spark-chart-components/stencil.config.ts
packages/genesys-spark-components/stencil.config.ts

added explicit dev server root

chore(other): added explicit dev server root

---

packages/genesys-spark-chart-components/stencil.config.ts
packages/genesys-spark-components/.gitignore
packages/genesys-spark-components/eslint.config.mjs
packages/genesys-spark-components/stencil.config.ts

test(other): fix e2e tests

---

packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor-beta.tsx
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor.scss

remove gap when there is no toolbar present
[✅ Closes: COMUI-3659](https://inindca.atlassian.net/browse/COMUI-3659)

fix(rich-text-editor-beta): remove gap when there is no toolbar

---

packages/genesys-spark/rollup.config.js

chore(other): fixed dev build

---

packages/genesys-spark-components/src/components/beta/gux-selector-cards/gux-selector-card/gux-selector-card.scss

removed explicit width
✅ Closes: COMUI-3637

fix(selector-card-beta): removed explicit width

---

packages/genesys-spark-components/src/components/stable/gux-truncate/example.html
packages/genesys-spark-components/src/components/stable/gux-truncate/gux-truncate.scss
packages/genesys-spark-components/src/components/stable/gux-truncate/gux-truncate.tsx
packages/genesys-spark-components/src/components/stable/gux-truncate/readme.md

added new tooltip-placement attribute
✅ Closes: COMUI-3707

feat(truncate): added new tooltip-placement attribute

---

package-lock.json
packages/genesys-spark-components/package.json

updated @floating-ui/dom to latest

chore(other): updated @floating-ui/dom to latest

---

packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.scss
packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.tsx
packages/genesys-spark-components/src/components/stable/gux-calendar/tests/__snapshots__/gux-calendar.spec.ts.snap

chore(calendar): Focus logic added to header buttons

---

packages/genesys-spark-components/src/components/stable/gux-context-menu/gux-context-menu.scss

fix(context-menu): Make inline-size of compact variant 24px

---

packages/genesys-spark-components/src/components/beta/gux-tooltip-base/gux-tooltip-base.tsx
packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/gux-pagination-items-per-page-legacy/tests/__snapshots__/gux-pagination-items-per-page.spec.ts.snap
packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/tests/__snapshots__/gux-pagination.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/tests/__snapshots__/gux-dropdown-multi.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-dropdown/tests/__snapshots__/gux-dropdown.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/gux-option-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option-icon/gux-option-icon.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox/options/gux-option/gux-option.tsx
packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-items-per-page/tests/__snapshots__/gux-pagination-items-per-page.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.tsx

https://inindca.atlassian.net/browse/COMUI-3750

feat(dropdown) - set the initial tooltip placement to the right

---

packages/genesys-spark-components/package.json
packages/genesys-spark-components/scripts/list-e2e-only-files.js

added script to identify missing Playwright tests
✅ Closes: COMUI-3598

chore(other): added script to identify missing Playwright tests

---

packages/genesys-spark-components/src/utils/decorator/on-resize.ts
web-apps/genesys-spark-examples/src/component-listing/app.js

fix(other): added requestAnimationFrame into OnResize decorator

---

packages/genesys-spark-components/src/utils/decorator/on-resize.ts

revert OnResize change causing jest issues
✅ Closes: COMUI-3830

fix(other): revert OnResize change causing jest issues

---

packages/genesys-spark-components/src/components/stable/gux-button-slot/example.html

update example page
✅ Closes: COMUI-3850

chore(button-slot): update example page

---

packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar.scss

fix(avatar-focusable-beta): reduce clickable space

---

devops/examples/pipeline.d/service.yml
web-apps/genesys-spark-examples/Jenkinsfile

This is a hack becasue skynet does not work with github and uses the npm-utils repo instead

ci(other): release hack

---

devops/assets/pipeline.d/deploy.yml
devops/examples/pipeline.d/service.yml

chore(other): fix pipeline

---

packages/genesys-spark-components/src/components/beta/gux-avatar-group/gux-avatar-overflow/gux-avatar-overflow.tsx
packages/genesys-spark-components/src/components/beta/gux-popover-beta/gux-popover.tsx
packages/genesys-spark-components/src/components/beta/gux-popover-beta/tests/gux-popover.spec.ts
packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/gux-popover-list.tsx
packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/tests/gux-popover-list.spec.ts
packages/genesys-spark-components/src/components/beta/gux-rich-text-editor/gux-rich-text-editor-list/gux-rich-text-editor-sub-list/gux-rich-text-editor-sub-list.tsx
packages/genesys-spark-components/src/components/beta/gux-tooltip-base/gux-tooltip-base.tsx
packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.tsx
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-flyout-menu.tsx
packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-menu/gux-submenu/gux-submenu.tsx
packages/genesys-spark-components/src/components/stable/gux-popover-list/gux-popover-list.tsx
packages/genesys-spark-components/src/components/stable/gux-popover-list/tests/gux-popover-list.spec.ts
packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.tsx
packages/genesys-spark-components/src/components/stable/gux-popover/tests/gux-popover.spec.ts
packages/genesys-spark-components/src/components/stable/gux-popup/gux-popup.tsx
packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.tsx

fixed memory leak
✅ Closes: COMUI-3871

fix(tooltip): fixed memory leak

---

Jenkinsfile

improved the jenkins job description

chore(other): improved the jenkins job description

---

packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.scss

Fixed issue where there was a double focus ring on the country code and input elements.
✅ Closes: COMUI-3415

chore(form-field-phone): Fixed issue with double focus ring inputs

---

packages/genesys-spark-components/src/components/stable/gux-badge/gux-badge.tsx

fix(badge): Update screenreader text when text altered by JS

---

packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.tsx
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/tests/__snapshots__/gux-form-field-range.e2e.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/tests/__snapshots__/gux-form-field-range.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/tests/gux-form-field-range.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/tests/gux-form-field-range.spec.ts

chore(form-field-range): Added tests

---

packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/gux-tab-advanced/gux-tab-advanced.tsx
packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/tests/__snapshots__/gux-tabs-advanced.spec.ts.snap
packages/genesys-spark-components/src/components/stable/gux-tabs-advanced/tests/gux-tabs-advanced.e2e.ts

chore(tabs-advanced): Fixed axe-violation

---

packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.tsx
packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/tests/__snapshots__/gux-copy-to-clipboard.spec.ts.snap

button not clickable via keyboard in nvda
✅ Closes: COMUI-3863

fix(copy-to-clipboard): button not clickable via keyboard in nvda

---

packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.tsx
packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.tsx

following wcag guidance for opening action buttons https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions/#:~:text=Keyboard%20Support-,Menu%20Button,-Key

fix(button-multi): open dropdown on enter and arrow key

---

packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx

chore(dropdown): use getOptionDefaultSlot for selected text

---

packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/example.html
packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/readme.md
packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/tests/gux-dropdown-multi.e2e.ts
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.scss
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-option-multi/gux-option-multi.scss
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-select-all/gux-select-all.scss
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-select-all/gux-select-all.tsx
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-select-all/i18n/en.json
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-select-all/readme.md
packages/genesys-spark-components/src/components/stable/gux-listbox-multi/readme.md
packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.service.ts
packages/genesys-spark-components/src/components/stable/gux-truncate/readme.md
packages/genesys-spark-components/src/i18n/translations/en.json

https://inindca.atlassian.net/browse/COMUI-3923

feat(gux-select-all) - addition of gux-select-all feature for dropdown-multi

---

packages/genesys-spark-components/src/components/stable/gux-form-field/helper-components/gux-form-field-input-clear-button/gux-form-field-input-clear-button.tsx

fixed clear buttons tooltip
✅ Closes: COMUI-4105

fix(form-field-search): fixed clear buttons tooltip

---

packages/genesys-spark-tokens/data/semantic/global.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-flare-dark.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-flare-light.json
packages/genesys-spark-tokens/snapshot/json/gse-ui-legacy-light.json
packages/genesys-spark-tokens/snapshot/scss/gse-ui-flare-dark.scss
packages/genesys-spark-tokens/snapshot/scss/gse-ui-flare-light.scss
packages/genesys-spark-tokens/snapshot/scss/gse-ui-legacy-light.scss
packages/genesys-spark/snapshot/css/flare/ui.css
packages/genesys-spark/snapshot/css/legacy/ui.css
packages/genesys-spark/snapshot/css/ui.css
packages/genesys-spark/snapshot/ui.css

refactor(other): fixed token collision

---

package-lock.json
packages/genesys-spark-chart-components/package.json
packages/genesys-spark-components/package.json

update Stencil dependency to latest

chore(other): update Stencil dependency to latest

---

packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.tsx

improved error handling
✅ Closes: COMUI-4089

fix(icon): improved error handling

---

packages/genesys-spark-components/src/components/stable/gux-card/example.html

https://inindca.atlassian.net/browse/COMUI-4165

feat(card) - update example page stylings to match design system

---

.amazonq/agents/default.json
package-lock.json
packages/genesys-spark-components/package.json

update @vvo/tzdb dependency to latest

chore(other): update @vvo/tzdb dependency to latest

---

packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.tsx
packages/genesys-spark-components/src/components/stable/gux-toggle/tests/gux-toggle.e2e.playwright.ts
packages/genesys-spark-components/src/components/stable/gux-toggle/tests/gux-toggle.spec.ts

update aria-label when changed dynamically
✅ Closes: COMUI-4211

fix(toggle-slider): update aria-label when changed dynamically

---

packages/genesys-spark-components/jest.config.ts
packages/genesys-spark-components/src/utils/array/async-filter.spec.ts
packages/genesys-spark-components/src/utils/error/log-error.spec.ts
packages/genesys-spark-components/src/utils/number/clamp.spec.ts

excluding test files from coverage
✅ Closes: COMUI-4235

test(other): excluding test files from coverage
