- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.scss
Using a token for a focus style. This is a token issue from the work of reskinning the gux-form-field-radio component.
> fix(gux-form-field-radio): using token for focus style

- packages/genesys-spark-components/src/components/stable/gux-blank-state/gux-blank-state.tsx
Open to opinions on this change.
I removed the `gux-button-slot-beta` from the `shadowDOM` due to the fact that a user can have a `blank-state` without a call to action button. This will cause errors in the DOM. I think it would be better to just leave it up to the end user to slot a `gux-button` instead if needed ?
I am not sure if there was a reason behind using `gux-button-slot-beta` in shadowDOM.
[COMUI-2241](https://inindca.atlassian.net/browse/COMUI-2241)
[COMUI-2241]: https://inindca.atlassian.net/browse/COMUI-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(blank-state): remove gux-button-slot-beta from shadowDOM

- packages/genesys-spark-components/src/components/stable/gux-breadcrumbs/breadcrumb-item/gux-breadcrumb-item.less
Closes [COMUI-1756](https://inindca.atlassian.net/browse/COMUI-1756)
Breadcrumbs were using the default browser focus-visible styling and not ours. This fixes that
[COMUI-1756]: https://inindca.atlassian.net/browse/COMUI-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(breadcrumb): adding default focus styling to breadcrumb-item

- packages/genesys-spark/src/hosts.ts
- packages/genesys-spark/test/hosts.spec.ts
I had hoped to find a way to share this code with what's in `registerCustomElements` in the components package, but I couldn't find a good way to do it.
> fix(genesys-spark): ensure asset loading is done on the same domain for new regions

- packages/genesys-spark/src/index.ts
- packages/genesys-spark/src/intl.ts
- packages/genesys-spark/test/intl.spec.ts
- packages/genesys-spark/tsconfig.json
This adds date/time formatting functions that are proxies to the native Intl constructors, but can handle locale lookup on their own from our standard locale locations
COMUI-2431
> feat(genesys-spark): add date/time formatting utilities

- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.scss
- packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.scss
- packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.scss
Closes [COMUI-2465](https://inindca.atlassian.net/browse/COMUI-2465)
Firefox apparently doesn't support :host-context.
Using :has anywhere breaks the whole selector, including ones separated by a comma.
[COMUI-2465]: https://inindca.atlassian.net/browse/COMUI-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(dropdown,dropdown-multi,listbox): fixing focus in Firefox

- packages/genesys-spark-components/src/components/stable/gux-form-field/functional-components/gux-form-field-error/gux-form-field-error.scss
https://inindca.atlassian.net/browse/COMUI-2501
The error text and icon were not vertically aligned in their flex container for all form-field components.
**Before:** 
**After:**
> fix(gux-form-field): gux-form-field error text vertical alignment fix

- docs/migration-guides/v4/readme.md
I added some notes to the migration guide about the stability of CSS variables.
> docs(v4 migration): add notes about CSS variable support

- packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss
Design told us that they want us to hardcode the viewport styles in the gux-modal for now, so I removed some TODOs for viewport styles.
> chore(gux-modal): hardcoding viewport styles in modal for now

- packages/genesys-spark/package.json
I started to try the new `genesys-spark` package in the navigation app and TS wasn't finding the types. It'd be nicer if I could figure out how to get rollup and ts to put the `.js` and `.d.ts` files in the same spot, but after a trying a bunch of different suggestions with nothing working, I can't be bothered. They can live in different folders.
> fix(genesys-spark): make sure package.json points to generated d.ts

- packages/genesys-spark-components/src/components/stable/gux-content-search/gux-content-search.scss
Shrink text for long navigation info
GDS-2247
Does this need to be backported to V3?
> feat(content-search): shrink text for long navigation info

- docs/migration-guides/v4/gux-modal-legacy.md
- packages/genesys-spark-components/scripts/generate-component-data.js
- packages/genesys-spark-components/src/components/stable/gux-modal/example.html
- packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.tsx
- packages/genesys-spark-components/src/components/stable/gux-modal/readme.md
- packages/genesys-spark-components/src/components/stable/gux-modal/tests/gux-modal.spec.ts
This allows the modal to be rendered more easily in the open state, but avoids the pitfalls of the open attribute on the native dialog element by calling `showModal` and `close` behind the scenes.
For folks who were curious from our previous discussion, the dialog HTML spec [outlines why it's preferred to use methods](https://html.spec.whatwg.org/multipage/interactive-elements.html#attr-dialog-open) over the attribute to show and close `<dialog>` elements.  The tl;dr is it makes the element do surprising things, but isn't an issue here since the property is just a proxy for the internal methods.
> feat(gux-modal): add an open property to the modal

- packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-picker.scss
- packages/genesys-spark-components/src/components/stable/gux-content-search/gux-content-search.scss
Add outline offset on focus
GDS-2250
Does this need to be backported to v3?
> feat(content-search month-picker): add outline offset on focus

- packages/genesys-spark-components/src/components/legacy/gux-action-toast-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-advanced-dropdown-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-disclosure-button-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-modal-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-notification-toast-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-simple-toast-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-switch-legacy/example.html
- web-apps/genesys-spark-examples/src/component-listing/app.js
Point migration guide links to the right place
Looks to come from the Resources section in bottom-left corner and all of the legacy components
> feat(migration guide links): point migration guide links to the right place

- packages/genesys-spark-components/README.md
- packages/genesys-spark-components/documentation/COMPONENT_EVOLUTION.md
Some links in the genesys-spark-components readme were broken, I've updated these to their new targets where possible. 
I couldn't find a react integration guide so I took that out. Also, added a link to the migration guide just since it's topical. 
Just to be clear, since they're not linked to GitHub this might still not work on npm (it doesn't currently either). I can replace the relative links with links there instead, just let me know what's prefered.
Update links to correct relative paths
> docs(genesys-spark-components readme): update links to correct relative paths

- packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss
Update datepicker focus style for calendar
GDS-2248
Does this need to be backported to V3?
> feat(datepicker): update datepicker focus style for calendar

- packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.tsx
console errors if target element removed first
to be backported
[COMUI-2416](https://inindca.atlassian.net/browse/COMUI-2416)
[COMUI-2416]: https://inindca.atlassian.net/browse/COMUI-2416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(popover): console errors if target element removed

- packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.tsx
First item does not receive focus automatically on filter
GDS-2271
Does this need to be backported to v3?
> feat(listbox): first item does not receive focus automatically on filter

- packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-calendar.scss
This fixes the popup positioning issue identified in COMUI-2453 when the popup is placed above the `gux-month-picker`. I am not exactly sure why the height is affecting it not to reposition correctly but I also think we probably do not need a fixed height on the `gux-month-calendar`. We did not have a fixed height in `v3`
[COMUI-2453](https://inindca.atlassian.net/browse/COMUI-2453)
[COMUI-2453]: https://inindca.atlassian.net/browse/COMUI-2453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(month-picker): popup positioning bug

- Jenkinsfile
- jenkinsfiles/components.Jenkinsfile
- jenkinsfiles/react.Jenkinsfile
- packages/genesys-spark-components-react/Jenkinsfile
By default the published `maintenance/v3` versions are given the npm dist tag "latest". This conflicts with the v4 npm published versions, which are also being tagged as "latest". In this PR, I added the "maintenance" dist tag for npm publishes from the v3/maintenance branch.
> chore(jenkinsfile): add maintenance tag to v3 npm publish

- packages/genesys-spark-components/src/components/stable/gux-table/example.html
After investigating the different possible solutions I thinks its best to just have an example on the examples page instead of going down the route of attributes which started to get messy as I was attempting to do it as columns can be different widths etc. 
The example in this PR is just for a basic data table but I can see potentially developers trying to use this with `resizable-columns` which will add a bit more complexity and discussion to this task.
> feat(table) - Addition of fixed column table example

- web-apps/genesys-spark-examples/Jenkinsfile
I'm not sure if this one line change is enough to fix the issue we are having with the maintenance/v3 branch docs deploy. Any feedback is appreciated here
> chore(jenkinsfile): docs maintenance branch should not be MAINLINE build

- packages/genesys-spark-components/src/components/stable/gux-action-button/gux-action-button.tsx
- packages/genesys-spark-components/src/components/stable/gux-action-button/tests/__snapshots__/gux-action-button.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-button-multi/gux-button-multi.tsx
- packages/genesys-spark-components/src/components/stable/gux-popup/gux-popup.tsx
- packages/genesys-spark-components/src/components/stable/gux-popup/readme.md
Added a `placement` property in `gux-popup` component and then passed `bottom-end` as the `placement` value to `gux-popup` from `gux-action-button` and `gux-button-multi`. This was done in order to right align the popup below these two components, instead of being left aligned before.
https://inindca.atlassian.net/browse/COMUI-2492
> fix(gux-action-button): changed placement to bottom-end

- web-apps/genesys-spark-examples/Jenkinsfile
This is a preventative measure to prevent `maintenance/v4` docs from having a mainline build type
> chore(jenkinsfile): docs maintenance release branch build type

- packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.constants.ts
- packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.tsx
Identified that the container widths were not calculating correctly. For example if you were to console log `controlWidth` within the `recordLayoutMinSize` function onload you will get a width of `562px` which is incorrect and should be `590px`. By including a delay of `1` second when the component loads you will retrieve the correct widths.
This then lead to refactors to the resizing behaviour as it was not condensing correctly.
Open to suggestions on this change.
This will need to be **backported** also
https://inindca.atlassian.net/browse/COMUI-2581
> feat(toolbar) - fix table toolbar not condensing correctly

- packages/genesys-spark-tokens/data/tokens.json
- packages/genesys-spark-tokens/snapshot/css/gse-ui.css
- packages/genesys-spark-tokens/snapshot/json/gse-ui.json
- packages/genesys-spark-tokens/snapshot/less/gse-ui.less
- packages/genesys-spark-tokens/snapshot/scss/_gse-ui.scss
Remove tooltip target offset token as it is not used. Implemented in JS instead
> feat(tokens): Remove token that is not used in tooltip

- packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.scss
AM/PM button does not inherit visibility css property when set on component.
[COMUI-2659](https://inindca.atlassian.net/browse/COMUI-2659)
Needs to be **backported**
[COMUI-2659]: https://inindca.atlassian.net/browse/COMUI-2659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(time-picker): AM/PM button does not inherit visibility css property when set on component

- packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.service.ts
Date and time formatting should get now supplement region data from the browser.
This behavior is "feature toggled" using a cookie, called spark-enable-regional-dates. To test out the functionality, set document.cookie = 'spark-enable-regional-dates' in your console. I opened a separate browser and set the region to "en-GB"  in my system preferences. To check the region in your console, just type navigator.language. As expected, the 24 hr time formats look different in my browser depending if I'm using en-US or en-GB regions.
> chore(gux-time-picker): region aware date formatting

- packages/genesys-spark-components/src/components/beta/gux-tooltip-base/gux-tooltip-base.scss
- packages/genesys-spark-components/src/components/beta/gux-tooltip-base/gux-tooltip-base.tsx
- packages/genesys-spark-components/src/components/beta/gux-tooltip-base/readme.md
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/a11yManualChecklist.md
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/example.html
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/gux-tooltip-types.ts
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/gux-tooltip.tsx
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/readme.md
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/tests/__snapshots__/gux-tooltip.spec.ts.snap
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/tests/gux-tooltip.e2e.ts
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/tests/gux-tooltip.spec.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.scss
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-range/gux-form-field-range.tsx
Creates an internal, more powerful tooltip base component to share implementation between multiple components (currently only gux-tooltip and gux-form-field-range). This also removes arrow/ancho from the tooltip for the range component (that was removed from the design of the gux-tooltip) so there is a small visual change.
> feat(gux-form-field-range): create and use internal tooltip component to share implementation

- packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-calendar.tsx
- packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-picker.tsx
- packages/genesys-spark-components/src/genesys-spark-utils/get-closest-element.ts
- packages/genesys-spark-components/src/genesys-spark-utils/intl.ts
- packages/genesys-spark/src/utils/get-closest-element.ts
- packages/genesys-spark/src/utils/intl.ts
Date and time formatting should get now supplement region data from the browser.
This behavior is "feature toggled" using a cookie, called spark-enable-regional-dates. To test out the functionality, set document.cookie = 'spark-enable-regional-dates' in your console.
> chore(gux-month-picker): region aware date formatting

- packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.tsx
escape issue on safari and firefox
[COMUI-2691](https://inindca.atlassian.net/browse/COMUI-2691)
[COMUI-2691]: https://inindca.atlassian.net/browse/COMUI-2691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(modal): escape issue on safari and firefox

- packages/genesys-spark-tokens/data/tokens.json
- packages/genesys-spark-tokens/package.json
- packages/genesys-spark/package.json
**Overview:**
We had an issue yesterday where I pushed a changed from the `genesys-spark-tokens` packages where I removed one item from the `tokens.json` and pushed to git and I never updated the snapshots but for some reason the build still passed. The general consensus is that there is no test commands within the tokens package json file therefore no failure would have been picked up. 
**Testing:**
I am going to test a **token change** on this PR without running new-tokens data and see if the build fails which is should.
**Update from testing:**
The build will now fail you can see my commit below in which it failed.
I think we should add the `new-tokens-data` to the build process if thats possible so that we dont encounter this issue ? …
> fix(tokens): add test command to package json

- packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.tsx
first keypress after focus should be treated as new input
To be **backported**
[COMUI-2616](https://inindca.atlassian.net/browse/COMUI-2616)
[COMUI-2616]: https://inindca.atlassian.net/browse/COMUI-2616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(datepicker): first keypress after focus should be treated as new input

- packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss
Closes https://inindca.atlassian.net/browse/COMUI-2690
I added 5px of padding to the right and left of the content slot. Doing this allows focusable elements to not be cut off on the left and right sides. I realize we could also ask the client to add spacing on their end instead of doing it inside the gux-modal component. Thoughts on adding spacing like I did and if so what kind of value makes sense? I feel like 5px is arbitrary. Should we use a token?
^^ **Update**: Daragh pushed a commit that makes the above not relevant anymore since the initial padding change I made had changed the design which we do not want.
> fix(gux-modal): added space around content slot

- packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-list/gux-month-list.tsx
- packages/genesys-spark-components/src/components/beta/gux-month-picker/tests/__snapshots__/gux-month-picker.spec.ts.snap
These issues were found in the latest axe tools `4.8.4`. When reviewing there was 2 critical issues one was linked to the `aria-selected` on the `gux-month-list-item` component. I think this is valid and does not need to be removed. The other was linked to the `renderFocusTarget` method which renders a span with a `tabindex="1"`. I am not sure this is needed but I may be wrong but I could not figure what it was used for. This `renderFocusTarget` method is also used within the `gux-list` component.
I did a quick scan of other components and there seems to be critical issues in others also such as `tabs-advanced` maybe they can be addressed in a separate ticket ?
[COMUI-2417](https://inindca.atlassian.net/browse/COMUI-2417)
[COMUI-2417]: …
> fix(month-picker): axe critical issues

- packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.tsx
first keypress after focus should be treated as new input
[COMUI-2616](https://inindca.atlassian.net/browse/COMUI-2616)
[COMUI-2616]: https://inindca.atlassian.net/browse/COMUI-2616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(date-picker): first keypress after focus should be treated as new input

- packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.tsx
On the docs site, the modal can't be reopened once closed as closing doesn't change the this.open prop.
> feat(modal): allow modal to be reopened

- packages/genesys-spark-components/src/components/stable/gux-accordion/gux-accordion-section/gux-accordion-section.scss
Closes https://inindca.atlassian.net/browse/COMUI-2763
The user was not able to highlight/select text in the accordion content and header, which is now fixed.
> fix(gux-accordion): allowing user to highlight text

- packages/genesys-spark-components/src/components/stable/gux-popover-list/gux-popover-list.tsx
✅ Closes: COMUI-2735
Closing popover-list on tab key press. Before, pressing the tab key would not close the popover-list within a tabs-advanced component.
Here's a video showing how you can test this functionality. The way I test it is tabbing to a 3 vertical dot icon in one of the tab headers and pressing enter, and then hitting tab again to try and focus out of the popover-list component. The bug I fixed was only present when using the keyboard to navigate to the popover-list, rather than using the mouse which didn't cause the bug to appear.
https://github.com/MyPureCloud/genesys-spark/assets/127438502/92429cb6-e74b-4c5c-a8bf-25e0f02733e3
> fix(tabs-advanced): Closing popover list on tab press

- packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss
- packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.tsx
- packages/genesys-spark-components/src/components/stable/gux-modal/tests/__snapshots__/gux-modal.spec.ts.snap
Instead of conditionally rendering footer slots this change will render the slots & hide using CSS where appropriate.
> feat(modal): using css to show or hide the button footer

- packages/genesys-spark-components/src/components/stable/gux-table/gux-table.light.scss
Additional CSS rule to make the table row hover on the darker rows more robust & difficult to override.
> feat(table): improving table row hover

- packages/genesys-spark-components/src/components/stable/gux-table/example.html
- packages/genesys-spark-components/src/components/stable/gux-table/gux-table.light.scss
This will provide default & hover colours on table rows even when sticky removing the necessity to add them separately.
> feat(table): applying styles to whole row even with sticky columns

- packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/gux-pagination-cursor.tsx
- packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination.tsx
- packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination.types.ts
**Note**
Prior to `V4` beta imported from stable and after `V4` stable became legacy and beta became stable so that is the reason for the current stable importing from legacy but is no longer needed as legacy will be outdated.
✅ Closes: COMUI-2888
> fix(pagination): remove legacy types import

- packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.tsx
✅ Closes: COMUI-1636
For now, you can paste this for the example page content to test the functionality added for this PR.
To test this PR, you can move focus into an element in the popover using the tab key to get there, and then move focus out of the popover by using the tab key or shift + tab and you should see the popover become hidden when you move focus out of the popover.
```
<h1>gux-popover</h1>
<div class="scroll-container">
<div class="scroll-interior">
<div id="popover-target">Example Element</div>
<gux-popover
id="popover-example"
position="top"
for="popover-target"
is-open
>
<span slot="title">Title</span>
<div class="popover-content-wrapper">
<div>Popover Content</div>
<div class="popover-content">
<gux-button accent="ghost" onclick="notify(event)">
Action 3
</gux-button> …
```
> fix(popover): Closing popover on focus out

- packages/genesys-spark-components/src/components/stable/gux-tooltip-title/tests/__snapshots__/gux-tooltip-title.e2e.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-tooltip-title/tests/gux-tooltip-title.e2e.ts
- packages/genesys-spark-components/src/components/stable/gux-truncate/gux-truncate.scss
- packages/genesys-spark-components/src/components/stable/gux-truncate/gux-truncate.tsx
- packages/genesys-spark-components/src/components/stable/gux-truncate/tests/gux-truncate.e2e.ts
✅ Closes: COMUI-1408
Let me know if there are any other tests you think I should write for `gux-truncate` and `gux-tooltip-title`.
> chore(tooltip): Added tests for gux-tooltip-title component

- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/example.html
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/tests/__snapshots__/gux-tooltip.spec.ts.snap
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/tests/gux-tooltip.e2e.ts
- packages/genesys-spark-components/src/components/beta/gux-tooltip-beta/tests/gux-tooltip.spec.ts
A div cannot be nested inside a paragraph, replacing with span.
> docs(tooltip-beta): fixing invalid html

- packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/gux-pagination-buttons-legacy/tests/__snapshots__/gux-pagination-buttons.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/__snapshots__/gux-form-field-checkbox.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/tests/__snapshots__/gux-form-field-color.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/tests/__snapshots__/gux-form-field-number.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/tests/__snapshots__/gux-form-field-phone.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/tests/__snapshots__/gux-form-field-radio.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-search/tests/__snapshots__/gux-form-field-search.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-select/tests/__snapshots__/gux-form-field-select.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/tests/__snapshots__/gux-form-field-text-like.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-textarea/tests/__snapshots__/gux-form-field-textarea.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-picker/tests/__snapshots__/gux-form-field-time-picker.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-time-zone-picker/tests/__snapshots__/gux-form-field-time-zone-picker.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/functional-components/gux-form-field-error/gux-form-field-error.scss
- packages/genesys-spark-components/src/components/stable/gux-form-field/functional-components/gux-form-field-error/gux-form-field-error.tsx
-Error message icon change
-Error message icon and text container gap change
-Error message icon and text container alignment when text is multi-line - error icon now is positioned at the top of the container instead of the middle. To test this you can add multi-line text in the example page for a component like form-field-checkbox like in the screenshot below:
✅ Closes: COMUI-2766
> chore(form-field-checkbox): Design changes for error message and icon

- packages/genesys-spark-components/src/components/stable/gux-calendar/gux-calendar.scss
**Notes**
Some months in the calendar will cause the calendar height to change when clicking the forward or back buttons which can cause the popover to close easily. Some months that you can see this on are  June, March, September, December for example. They have an extra row causing the height of the calendar to be bigger.
See video here :  https://inindca.atlassian.net/browse/COMUI-2915
To be **backported**
✅ Closes: COMUI-2915
> fix(calendar): addition of fixed height to calendar

- packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.scss
**Notes**
Since `opacity` will be 0 to begin with it through the use of the `@mixin gux-toolbar-prevent-initial-flicker-workaround` will create a new stacking context which will cause the issue seen in the ticket above. The tooltip and popup seem to be obscured by other elements.
https://www.w3.org/TR/css-color-3/#transparency
**Ticket**
https://inindca.atlassian.net/browse/COMUI-2924
table-toolbar tooltip/popup now appear over other gux-components
✅ Closes: COMUI-2924
> fix(table-toolbar): table-toolbar tooltip/popup now appear over other gux components

- packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.tsx
There was an issue when clicking an element within the popover after focus is on another element within the popover was triggering the focus out event and closing the popover, which wasn't expected behavior. This PR fixes this issue.
✅ Closes: COMUI-1471
> fix(popover): Fixed gux-popover dismiss logic on focus out

- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/example.html
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/gux-form-field-radio-group.scss
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/readme.md
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/tests/gux-form-field-radio-group.e2e.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/gux-form-field-radio.scss
Does anyone know why the following does not set the `padding-top` of the first `gux-form-field-radio` element to 0? I just need a way to set the padding top of all the slotted `gux-form-field-radio` elements except the first and I cannot get it to work. any input would be appreciated, thanks
```
::slotted(gux-form-field-radio) {
padding-top: var(--gse-ui-formControl-group-gapItems);
&:first-child {
padding-top: 0;
}
}
```
> fix(form-field-radio-group): update radio group spacing

- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-select/gux-form-field-select.scss
Ticket : https://inindca.atlassian.net/browse/COMUI-2955
This issue also exists in other components such as `form-field-number` , `form-field-phone`, `form-field-text-like`.  I wanted to discuss here before making changes to these components also.
The issue is that the slotted `input` in these components only has a height of 16px whereas the parent of the slotted input which is `.gux-input-container` class has a height of 32px meaning that if you are to click in any area outside of the 16px height bounds of the slotted input it wont select that component. I have attatched an image below as an example,
I think to fix this issue we would instead need to apply the 32px height to the actual slotted input and not the `.gux-input-container` class.
✅ Closes: COMUI-2955
> fix(form-field-select): clicking downarrow now displays the dropdown

- packages/genesys-spark-components/src/components/stable/gux-table/gux-table.scss
**Ticket** :  https://inindca.atlassian.net/browse/COMUI-2951
**Reproduction Steps:**
1. Go to `gux-context-menu` and  under the `Table Example` click the furtherest right arrow on the pagination so that the arrow buttons are now disabled. Then click the `gux-context-menu` to open and the issue should appear. See screenshot below,
**Issue** 
1. This issue is being caused due to the opacity property being set on the disabled element. If the opacity property has a value of less than `1` it will create a new stacking context as see in the screenshot above. Outlined here (https://www.w3.org/TR/css-color-3/#transparency)
**Resolution**
The `gux-table` uses the `isolation:isolate` property which was introduced to fix https://inindca.atlassian.net/browse/COMUI-562.
The `isolation` property with …
> fix(table): disabled pagination overlapping context-menu

- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file/example.html
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file/gux-form-field-file.scss
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file/gux-form-field-file.tsx
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file/i18n/en.json
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file/tests/__snapshots__/gux-form-field-file.e2e.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file/tests/__snapshots__/gux-form-field-file.spec.ts.snap
- packages/genesys-spark-components/src/i18n/translations/en.json
✅ Closes: COMUI-2969
This is really small stuff but it helps with the tooltip changes that are coming also. Basically removing some duplication on the screenreader content and changing the example to make the ids unique.
> fix(form-field-file): Remove duplication in screenreader content

- packages/genesys-spark-components/src/components/stable/gux-icon/docs/current.html
- packages/genesys-spark-components/src/components/stable/gux-icon/docs/deprecated.html
- packages/genesys-spark-components/src/components/stable/gux-icon/docs/legacy.html
- packages/genesys-spark-components/src/components/stable/gux-icon/docs/restricted.html
- packages/genesys-spark-components/src/components/stable/gux-icon/docs/spark.html
- packages/genesys-spark-components/src/components/stable/gux-icon/example.html
- web-apps/genesys-spark-examples/webpack.config.js
Too many icons on a single page takes too long to render (if they even render at all).
So I've split the icons into multiple pages.
Pages placed inside a 'docs' folder are generated & can be linked to.
Not perfect but it's an improvement.
Maybe other components could do with having sub-pages.
I will take another look at improving this in the near future, maybe an improved nav or adding them to the menu.
> docs(icon): splitting icons into multiple pages

- packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.tsx
"setAttribute not a function" error when setting decorative programmatically in firefox
[
✅ Closes: COMUI-2933](https://inindca.atlassian.net/browse/COMUI-2933)
> fix(icon): "setAttribute not a function" error when setting decorative programmatically in firefox

- packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.tsx
Ticket : https://inindca.atlassian.net/browse/COMUI-2873
**RCA** 
What I believe was happening is that the  `Watch('value')` is firing before the `componentWillLoad()` lifecycle function which seems weird but this can happen in scenarios where the `value` is set programmatically like it is in this issue as far as I researched. When the `Watch('value')` is fired it called `this.updateDate()` which needs the `this.format` to be set  which it wont be since the format is set in `componentWillLoad()` I think the two ways around this are to apply an `if` guard to the `Watch('value')` or provide a default format where the state is created. I opted for the `if` guard.
**To be backported**
✅ Closes: COMUI-2873
> fix(datepicker): ensure format is set before updating date

- packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/example.html
- packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/gux-pagination-cursor.tsx
- packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/readme.md
- packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/tests/__snapshots__/gux-pagination-cursor.e2e.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/tests/__snapshots__/gux-pagination-cursor.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/tests/gux-pagination-cursor.e2e.ts
- packages/genesys-spark-components/src/components/stable/gux-pagination-cursor/tests/gux-pagination-cursor.spec.ts
New 'controls' prop to pass an ID of the 'controlled' element to the buttons to establish a reference.
Throwing a warning if the prop not present.
Aria-controls "Identifies the element (or elements) whose contents or presence are controlled by the current element."
https://w3c.github.io/aria/#aria-controls
Some screenreaders allow the virtual cursor to return its focus to the controlled element.
> feat(pagination-cursor): allowing reference to controlled element

- packages/genesys-spark-components/src/components/stable/gux-pagination/gux-pagination-buttons/gux-pagination-ellipsis-button/gux-pagination-ellipsis-button.tsx
The slotted input of type number within the `gux-pagination` for the `goToPage` functionality allows for extra characters outside of numbers including `e` , `E`, `+`, `.` and `-`. This is normal and part of the native input number. I have filtered out these characters from the input. I have also added the fix to not allow for an empty input to be submitted.
[✅ Closes: COMUI-2991](https://inindca.atlassian.net/browse/COMUI-2991)
> fix(pagination): filter out characters from slotted number input

- packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-buttons-beta/gux-pagination-ellipsis-button/gux-pagination-ellipsis-button.tsx
I think this should be backported. Backport of https://github.com/MyPureCloud/genesys-spark/pull/545
[COMUI-2991](https://inindca.atlassian.net/browse/COMUI-2991)
[COMUI-2991]: https://inindca.atlassian.net/browse/COMUI-2991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(pagination-beta): filter out characters from slotted number input

- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox-group/example.html
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/example.html
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio-group/example.html
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/example.html
Update the example html files to match UX usage guidelines for the `form-field-checkbox-group-beta` and the `form-field-radio-group-beta` components.
**Question**: Is it enough to just update the example file to match UX guidelines? Or should we add `log warn` for combinations of uses that are not part of the UX guidelines? 
For example, a UX guideline is that the Error text slot should override the Help text slot. Should we add logic to the component to constrain users to this usage guideline?
It is my inclination to not impose strict usage guidelines within the component itself, instead we just update the examples so that users follow the best practices.
> docs(form-field-radio-group): update html file to reflect UX guidelines

- packages/genesys-spark-components/src/components/beta/gux-time-zone/example.html
- packages/genesys-spark-components/src/components/beta/gux-time-zone/gux-time-zone.service.ts
- packages/genesys-spark-components/src/components/beta/gux-time-zone/gux-time-zone.tsx
- packages/genesys-spark-components/src/components/beta/gux-time-zone/readme.md
- packages/genesys-spark-components/src/components/beta/gux-time-zone/tests/gux-time-zone.service.spec.ts
- packages/genesys-spark-components/src/components/beta/gux-time-zone/tests/gux-time-zone.spec.ts
This component was added to v3 but never v4 back in September 2023. There was a request to add it to v4 and I don't see any obvious reason not to but I'm open to correction. 
✅ Closes: COMUI-2956
> feat(time-zone): Add gux-time-zone to v4

- packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.scss
- packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.scss
remove default box-shadow style, should only be applied to the `gux-dropdown` use case as confirmed by UX.
✅ Closes: COMUI-3012
https://inindca.atlassian.net/browse/COMUI-3012
> style(listbox): remove default box-shadow style

- packages/genesys-spark-components/src/components/beta/gux-avatar/gux-avatar.tsx
- packages/genesys-spark-components/src/components/beta/gux-avatar/tests/__snapshots__/gux-avatar.spec.ts.snap
remove `title` attribute from `abbr` element.
**Notes**
By having both the `title` attribute and `aria-label` attribute on the `abbr` element this causes an wcag violation.
https://dequeuniversity.com/rules/axe/4.9/aria-prohibited-attr?application=axeAPI
Removed `title` attribute as assistive  technologies like screen readers do not generally announce the `title` attribute.
By removing the `title` attribute this will remove the tooltip which shows text expansion but tooltips will be incorporated at a later stage.
✅ Closes: COMUI-3034
> fix(avatar): remove title attribute from abbr element

- packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss
**Note**
The dialog element had both vertical and horizontal scrollbars. They are not needed as we currently have a vertical scrollbar on the modal content.
[✅ Closes: COMUI-3027](https://inindca.atlassian.net/browse/COMUI-3027)
> fix(modal): remove scrollbars from dialog element

- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.scss
- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.tsx
- packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.scss
- packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx
**Note**
You can reproduce this issue by setting the `disabled` attribute on the dropdown using a `setTimeout`.  You will need to remove my changes to see this.
Added disabled checks to dropdown and dropdown multi
[✅ Closes: COMUI-3052](https://inindca.atlassian.net/browse/COMUI-3052)
> fix(dropdown): filterable dropdown/multi disabled state not updating correctly

- packages/genesys-spark-components/src/components/stable/gux-modal/gux-modal.scss
Apply padding-top to modal-header instead of container. The ticket also mentions that the `dialog` element has scrollbars but these were removed in a previous PR.
✅ Closes: COMUI-2998
> style(modal): dynamic gux-modal footer buttons getting cut off 

- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.tsx
- packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx
**Note**
I went with the same pattern we use across different components like `gux-toggle` that when the component is `loading` it should be in a disabled state so the user cannot interact with it.
I did not apply this change to the `filterable` dropdown as I think it did not make sense to but I am open to opinions. 
I will loop UX in as-well to get some of there input on what is the expected behaviour.
[✅ Closes: COMUI-3063](https://inindca.atlassian.net/browse/COMUI-3063)
> fix(dropdown): dropdown is now disabled when loading non-filterable list

- packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.scss
The `gux-toolbar-flicker-workaround` mixin was creating an unnecessary stacking context so I switched to use visibility instead with the same delay to prevent the flicker and removed the `z-index` also which will not be needed on the toolbar anymore. I probably should have chose `visibility` over `opacity` when resolving this issue (https://github.com/MyPureCloud/genesys-spark/pull/505)
[✅ Closes: COMUI-3070](https://inindca.atlassian.net/browse/COMUI-3070)
> fix(table-toolbar): change mixin to not create a stacking context

- packages/genesys-spark-components/src/components/stable/gux-popover/example.html
✅ Closes: COMUI-3081
I asked UX if they could take a look at the time machine branch in this PR and Monse said the changes looked good. I told her that the changes I made were only in the example.html file for the component so the consumers of gux-popup would have to remember to use the gux-cta-group component in gux-popover's slotted content if they wanted multiple gux-button instances grouped.
> chore(popover): Using gux-cta-group to group content buttons

- packages/genesys-spark-components/src/components/beta/gux-cta-group/gux-cta-group.scss
You can now apply a width to the cta group & the buttons will truncate if necessary.
> feat(cta group): make responsive and allow buttons to truncate if necessary

- packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/tests/__snapshots__/gux-time-zone-picker.spec.ts.snap
- packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/tests/gux-time-zone-picker.spec.ts
set exact date for tests so that the tests don't fail during DST changes
> test(time-zone-picker): set exact date for tests

- packages/genesys-spark-components/src/components/beta/gux-visualization/gux-visualization.tsx
Fixes a memory leak in gux-visualization by calling the vega-embed finalize function to remove event listeners and other items.
> fix(gux-visualization): fix memory leak in gux-visualization

- Jenkinsfile
Closes [COMUI-2590](https://inindca.atlassian.net/browse/COMUI-2590)
[COMUI-2590]: https://inindca.atlassian.net/browse/COMUI-2590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build(npm-publish): adding logic to send email on failure of publish

- packages/genesys-spark-chart-components/src/components/beta/gux-visualization/gux-visualization.scss
**Note**
The reported also suggested adding the `::part` pseudo element to the `.gux-chart-container` div so they could add additional styles but I am not sure if this is a good idea.
[✅ Closes: COMUI-3166](https://inindca.atlassian.net/browse/COMUI-3166)
> fix(visualization): add height to chart container

- packages/genesys-spark-components/src/components/stable/gux-form-field/helper-components/gux-form-field-input-clear-button/gux-form-field-input-clear-button.scss
Update the `color` of the `button` element to be : `--gse-ui-formControl-input-inputIcon-iconEndColor`
One thing I noticed was that the token values are different to figma. In figma the tokens value is `#6A6D75` whereas in the repo it is `626e84`
I was just wondering what we should we do in this scenario should I just update the token value myself ?
[✅ Closes: COMUI-3176](https://inindca.atlassian.net/browse/COMUI-3176)
> style(other): Update color of form-field-input-clear-button

- packages/genesys-spark-chart-components/src/components/beta/gux-visualization/example.html
Add spark bar chart examples and streamline example generation a little. I also removed some examples that were not doing anything different.
✅ Closes: ENGAGEUI-8702
> docs(visualization): Add spark bar chart examples

- packages/genesys-spark-chart-components/src/components/beta/gux-visualization/gux-visualization.tsx
Adds the same fix (https://github.com/MyPureCloud/genesys-spark/pull/656) that was previously applied to v3. Calls finalize() on previous vega embed results when the chart component is rendered
✅ Closes: ENGAGEUI-9053
> fix(visualization): Add chart memory leak fix from components v3

- packages/genesys-spark-components/src/components/beta/gux-tooltip-base/gux-tooltip-base.tsx
- packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.tsx
- packages/genesys-spark-components/src/utils/dom/overflow-detection.ts
✅ Closes: COMUI-3077
```
<div
style="
width: 300px;
max-height: 200px;
overflow: auto;
border: blue 1px solid;
"
>
<gux-copy-to-clipboard>
<div slot="content">
cing elit. Ut mollis serus posuere a. Proin pel cing elit. Ut mollis serus
posuere a. Proin pel cing elit. Ut mollis serus posuere a. Proin pel cing
elit. Ut mollis serus posuere a. Proin pel cing elit. Ut mollis serus
posuere a. Proin pel cing elit. Ut mollis serus posuere a. Proin pel cing
elit. Ut mollis serus posuere a. Proin pel cing elit. Ut mollis serus
posuere a. Proin pellentesque suscipit erat, id maximus lorem consectetur
nec. Sed vel viverra.
</div>
</gux-copy-to-clipboard>
</div>
```
```
<div
style="
width: 300px;
max-height: 100px;
overflow: auto;
border: blue 1px solid;
"
>
<p style="margin: 0; padding: 12px 0;">
By …
```
> feat(copy-to-clipboard): detect overflow in tooltip position

- packages/genesys-spark-components/src/components/stable/gux-tabs/gux-tabs.tsx
**Note**
From what I could tell from the error and after inspecting the teams repository is that its an initialisation issue related to the `gux-tab-list`.  Sometimes the error will appear and other times it wont. As described in the ticket the tabs work as expected but its just the error that appears intermittently. This fix just adds a chaining operator to the`tabList` and `panel` to ensure no console error is emitted.
[✅ Closes: COMUI-3183](https://inindca.atlassian.net/browse/COMUI-3183)
> fix(tabs): check if tab-list is set on initialisation

- packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar-custom-action/gux-table-toolbar-custom-action.tsx
- packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.tsx
- packages/genesys-spark-components/src/components/stable/gux-table-toolbar/tests/__snapshots__/gux-table-toolbar.spec.ts.snap
always show label when in the condensed display
✅ Closes: COMUI-3213
> fix(table-toolbar): always show label when in the condensed display

- packages/genesys-spark-components/src/components/beta/gux-table/gux-table.tsx
The table select all status will now automatically update if a row is removed from the dom.
> BACKPORT: fix(table): updating select all status when row removed from dom

- packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle-slider/gux-toggle-slider.tsx
- packages/genesys-spark-components/src/components/stable/gux-toggle/gux-toggle.tsx
- packages/genesys-spark-components/src/components/stable/gux-toggle/tests/__snapshots__/gux-toggle.spec.ts.snap
The screen reader now will only read the "checked" label.
The longer term fix would be for UX to implement a change to the design so that the toggle label does not change when the toggle is pressed 
additional context here https://inindca.atlassian.net/browse/COMUI-3181
> fix(toggle): screen reader label set to checked label

- packages/genesys-spark-components/src/components/beta/gux-segmented-control/gux-segmented-control.tsx
fix disabled state from segmented-control items
[✅ Closes: COMUI-3369](https://inindca.atlassian.net/browse/COMUI-3369)
> fix(segmented-control): fix disabled state for segmented-control items

- packages/genesys-spark-components/src/components/beta/gux-popover-list-beta/gux-popover-list.tsx
> fix(popover-list-beta): Focus first list item on popover show

- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox-group/a11yManualChecklist.md
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/a11yManualChecklist.md
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/__snapshots__/gux-form-field-checkbox.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-checkbox/tests/gux-form-field-checkbox.spec.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/tests/__snapshots__/gux-form-field-color.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-color/tests/gux-form-field-color.spec.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file/tests/__snapshots__/gux-form-field-file.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-file/tests/gux-form-field-file.spec.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/tests/__snapshots__/gux-form-field-number.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-number/tests/gux-form-field-number.spec.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-radio/tests/__snapshots__/gux-form-field-radio.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-search/tests/__snapshots__/gux-form-field-search.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-search/tests/gux-form-field-search.spec.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-select/tests/__snapshots__/gux-form-field-select.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-select/tests/gux-form-field-select.spec.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/tests/__snapshots__/gux-form-field-text-like.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-text-like/tests/gux-form-field-text-like.spec.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-textarea/tests/__snapshots__/gux-form-field-textarea.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-textarea/tests/gux-form-field-textarea.spec.ts
- packages/genesys-spark-components/src/components/stable/gux-form-field/gux-form-field.service.ts
Adds 2 aria attributes to the form-field-checkbox & form-field-radio.
See: https://www.smashingmagazine.com/2023/02/guide-accessible-form-validation/
[aria-invalid](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid)
[aria-errormessage](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-errormessage)
aria-errormessage has partial support - https://a11ysupport.io/tech/aria/aria-errormessage_attribute
> feat(form-field-checkbox): adding aria attributes to help with error accessibility

- packages/genesys-spark-components/src/components/stable/gux-time-picker/gux-time-picker.tsx
✅ Closes: COMUI-3010
I wanted to see if the team thought this approach made sense. UX wanted the time dropdown to expand when clicking the padded area of the container, but I was having trouble wiring that up without adding a bunch of extra code. It seemed simpler to just focus the hour input on padded area click, but let me know what you all think.
> chore(time-picker): Focusing hour input on target container click

- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.scss
- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.tsx
- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/tests/__snapshots__/gux-dropdown-multi.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap
Accessibility failure due to a button nested inside a button.
Following the W3C combobox pattern
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/
> feat(dropdown-multi): accessibility improvement

- package-lock.json
- packages/genesys-spark-components-react/package.json
Update the peer dependencies to allow projects to use React 19 without warnings
> chore(packages/genesys-spark-components-react/package.json): update peer deps for React

- packages/genesys-spark-components/src/components/beta/gux-tooltip-base/gux-tooltip-base.scss
- packages/genesys-spark-components/src/components/stable/gux-tooltip/gux-tooltip.scss
**Note**
I re-added the animation delay of `350ms` for when showing the tooltip as this was causing issues with tooltips overlapping as the tooltip would show if you just brush over the target element. See video below, . I think this works fine and is outlined here to wait `0.3-5` so that you know the users intent when hovering over the target area (https://www.nngroup.com/articles/timing-exposing-content/#:~:text=Wait-,0.3%E2%80%930.5%20seconds.,-If%20cursor%20remains) . This does not regress the accessibility changes made in (https://inindca.atlassian.net/browse/COMUI-3420) so the user can still hover over the tooltip content.
https://github.com/user-attachments/assets/e7da9c97-1267-4c84-ab32-90534c4ff537
> fix(tooltip): add animation delay for when showing tooltip

- packages/genesys-spark-components/src/components/beta/gux-side-panel/gux-side-panel.scss
Removed the `display:flex` on the side-panel-content container as its not needed.
[✅ Closes: COMUI-3502](https://inindca.atlassian.net/browse/COMUI-3502)
> fix(side-panel-beta): remove flex display from content

- packages/genesys-spark-components/src/components/stable/gux-dropdown/gux-dropdown.tsx
✅ Closes: COMUI-3491
Here's an example for testing:
```
<gux-option value="us-east-1" id="gux-option-4qupoj7mux" role="option" class="gux-show-subtext gux-selected" aria-selected="true" aria-disabled="false" hydrated="">Americas (US East) (us-east-1)
<span slot="subtext">
https://login.mypurecloud.com</span>
</gux-option>
```
> fix(option): trim whitespace for subtext selection

- packages/genesys-spark-components/src/components/beta/gux-popover-beta/gux-popover.tsx
- packages/genesys-spark-components/src/components/stable/gux-popover/gux-popover.tsx
- packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.tsx
- packages/genesys-spark-components/src/utils/dom/get-slot.ts
getSlot function now only looks at direct children
✅ Closes: COMUI-3509
> fix(other): getSlot function now only looks at direct children

- packages/genesys-spark-components/src/components/beta/gux-popover-beta/gux-popover.tsx
There was a bug where the autofocused button was being clicked when popover is opened using 'enter' key. This pr fixes this by adding `event.preventDefault()` when opening the popover using the keyboard
> fix(popover-beta): add preventDefault when opening popover

- packages/genesys-spark-chart-components/src/genesys-spark-utils/intl.ts
- packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/gux-month-list/gux-month-list-item/readme.md
- packages/genesys-spark-components/src/components/beta/gux-month-picker/gux-month-calendar/readme.md
- packages/genesys-spark-components/src/components/beta/gux-month-picker/readme.md
- packages/genesys-spark-components/src/components/stable/gux-time-picker/readme.md
- packages/genesys-spark-components/src/genesys-spark-utils/intl.ts
- packages/genesys-spark/snapshot/index.js
- packages/genesys-spark/src/utils/intl.ts
- packages/genesys-spark/test/intl.spec.ts
Web directory and the login page are setting the English language as `en-us`, which means the browser locale logic is not being taken into account. For now, if the dom language is set as `en-us` we will change this to `en` so that the browser region can be applied. There is a future epic planned for these applications to migrate away from setting `en-us` and at that time we will remove this override logic.
> fix(other): update localization logic to treat `en-us` dom lang as `en`

- packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/gux-copy-to-clipboard.scss
COMUI-3518
There are behaviour questions that need to be worked out in relation to the tooltip also but this is something we should fix. 
Before:
tooltip can be reactivated by hovering over the area where it was previously shown
https://github.com/user-attachments/assets/c6856ccd-4a2d-4e00-8263-cd4a7673a7c1
After:
tooltip can be hovered over when displayed but when dismissed, it must be again triggered by the owning element 
https://github.com/user-attachments/assets/202b84f4-c79c-47a5-a9fc-9d52642152c1
> fix(copy-to-clipboard): display none on tooltip when hidden

- packages/genesys-spark-components/src/components/stable/gux-toast/gux-toast.scss
✅ Closes: COMUI-3635
To see the issue add this to docs:
```
<gux-toast toast-type="success">
<div slot="title">Success Example</div>
<div slot="message">accountswitcherdcatestuser2@account-switcherdca.test account successfully removed</div>
</gux-toast>
```
> fix(toast): Break word on message

- packages/genesys-spark-components/src/components/legacy/gux-action-toast-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-advanced-dropdown-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-disclosure-button-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-modal-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-modal-legacy/gux-modal-legacy.scss
- packages/genesys-spark-components/src/components/legacy/gux-notification-toast-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-pagination-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-simple-toast-legacy/example.html
- packages/genesys-spark-components/src/components/legacy/gux-switch-legacy/example.html
Updated `gux-modal-legacy` styles to support dark mode.
Updated the color of warning icons in `gux-modal-legacy` and `gux-toast-legacy`
> feat(styles): Updated styles on modal-legacy and example pages

- packages/genesys-spark-components/src/components/stable/gux-listbox-multi/gux-listbox-multi.tsx
- packages/genesys-spark-components/src/components/stable/gux-listbox/gux-listbox.tsx
**Steps to reproduce on the live docs**
1. Go to the `Unknown Value Set` dropdown where you add the Jellyfish option.
2. Set the `filter-type` to be `starts-with`
3. Click `Add Jellyfish Option`
4. You should see that the Jellyfish option does not appear in the `listbox-multi` list.
[✅ Closes: COMUI-3609](https://inindca.atlassian.net/browse/COMUI-3609)
> fix(dropdown-multi): add afterNextRender when slot content changes

- packages/genesys-spark-components/src/components/stable/gux-table-toolbar/gux-table-toolbar.tsx
✅ Closes: COMUI-3752
This PR fixes an issue where if you're in a condensed display layout and you increase the browser width, the permanent action buttons weren't moving from the menu actions dropdown to the root
> chore(table-toolbar): Fixed layout scaled up

- packages/genesys-spark-components/src/components/stable/gux-copy-to-clipboard/i18n/en.json
- packages/genesys-spark-components/src/i18n/translations/en.json
COMUI-3311
To test you can run this in the console and the click to see the error: 
`  navigator.clipboard.writeText = () => Promise.reject(new Error('Clipboard access denied'));`
> fix(copy-to-clipboard): Add longer error message

- packages/genesys-spark-components/src/components/beta/gux-popover-beta/example.html
- packages/genesys-spark-components/src/components/beta/gux-popover-beta/gux-popover.tsx
- packages/genesys-spark-components/src/components/beta/gux-popover-beta/readme.md
From my understanding of the ticket they have a `for` element which when they press the enter key renders the popover but the `autofocus` will not work due to the fact that the `gux-popover-beta` wont have been rendered therefore missing the `keydownHandler` that we have within the component.
Let me know if there is any drawbacks to this choice.
[✅ Closes: COMUI-3916](https://inindca.atlassian.net/browse/COMUI-3916)
> fix(popover-beta): add method to focus popover

- packages/genesys-spark/scripts/generate-component-data.mjs
- web-apps/genesys-spark-examples/src/component-listing/app.js
✅ Closes: n/a
Focus, z-index pages etc aren't showing in the docs site.
> chore(other): Display non-component examples in docs

- packages/genesys-spark-components/src/components/legacy/gux-switch-legacy/gux-switch-item/gux-switch-item.tsx
- packages/genesys-spark-components/src/components/legacy/gux-switch-legacy/tests/__snapshots__/gux-switch.spec.ts.snap
Even though this is a legacy component this is an accessibility fix that adds `aria-current` to the selected item
How do I update the snapshots locally? The npm command `npm run test.update-snapshot` in `genesys-spark-components` was not working
> fix(switch-legacy): add aria-current to selected item

- packages/genesys-spark-components/src/components/stable/gux-table/example.html
- packages/genesys-spark-components/src/components/stable/gux-table/gux-row-select/gux-row-select.tsx
- packages/genesys-spark-components/src/components/stable/gux-table/gux-row-select/readme.md
✅ Closes: COMUI-3913
This PR adds a new label API field to the gux-row-select component. If this new label prop is set then screenreaders will read out this label text instead of the default text that's currently being used. Does the name of this API property make sense or would `labelText` or `customLabel` or something else make more sense?
Also, does anyone know if there's another step I need to take to get this new API field in the next release? I thought I remember some other release file I have to modify when API changes are made but wanted to confirm with you all.
> feat(row-select): Added new label prop

- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.scss
- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/gux-dropdown-multi.tsx
- packages/genesys-spark-components/src/components/stable/gux-dropdown-multi/tests/__snapshots__/gux-dropdown-multi.spec.ts.snap
- packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-dropdown/tests/__snapshots__/gux-form-field-dropdown.spec.ts.snap
allow to filter dropdown-multi on focus
This is the same fix as was done in the below PR. Basically when you focus on the dropdown via keyboard it will allow you to immediately start typing. 
https://github.com/MyPureCloud/genesys-spark/pull/1165/files
✅ Closes: [COMUI-3860](https://inindca.atlassian.net/browse/COMUI-3860)
[COMUI-3860]: https://inindca.atlassian.net/browse/COMUI-3860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dropdown-multi): allow to filter dropdown-multi on focus

- packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.scss
Not perfect but is a quick improvement.
Resolves this issue:
> fix(datepicker): allow for a narrower width than the default to be applied

- packages/genesys-spark-components/documentation/COMPONENT_DESIGN.md
- packages/genesys-spark-components/src/components/beta/gux-phone-input/example.html
- packages/genesys-spark-components/src/components/stable/gux-dropdown/example.html
**Question**
Where do people think is the best place is to call out this difference? In the example pages of the components or in the readme  of `genesys-spark-components` or somewhere else ?
✅ Closes: COMUI-4128
> refactor(other): remove disabled=false from example docs
